# FBX -> .blend bake script (foreign-scene reference path). Generated by MayaSceneImport -- do not edit by hand.

"""Import an FBX headlessly and save it as a ``.blend`` so a foreign scene can be LINKED.

Blender can only link a ``.blend``, so *referencing* a foreign (Maya) scene needs one hop
more than importing it: the converted FBX is baked into a cached ``.blend`` here and the
Reference Manager links that. The mirror of mayatk's ``templates/_bake_scene.py`` (which
bakes an FBX to a cached ``.ma`` for ``cmds.file(reference=True)``).

Runs under ``blender --background --factory-startup --python`` via
``pythontk.run_script_to_artifact``, which judges success by the saved ``.blend``'s
existence, NOT the exit code (a ``--python`` script that raises does not change Blender's
exit code by default -- the ``os._exit`` below makes it honest).

The bake starts from an EMPTY factory scene (``read_factory_settings(use_empty=True)``):
the startup cube/camera/light would otherwise land in every linked library.

Materials: FBX carries only the classic model, so the conversion's ``.manifest.json``
sidecar is replayed through the SAME engine the direct-import path uses
(:meth:`MayaSceneImport._apply_texture_manifest`) rather than a second copy of that logic.
``EXTRA_SYS_PATH`` carries the parent Blender's ``sys.path`` into this child (same
Blender, same interpreter -- the entries are valid), so blendertk is normally importable.
When it is not, the bake still succeeds and keeps the FBX-carried materials (logged).

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Blender Python at module scope: no mayatk/blendertk/pythontk imports
# (only Blender's own bundled modules are guaranteed in the child process). blendertk is
# imported *optionally*, inside the manifest step, and its absence is never fatal.
import os
import re
import sys
import traceback

SRC_FBX = r"__SRC_FBX__"
OUT_BLEND = r"__OUT_BLEND__"
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__


def _extend_sys_path():
    """Make the parent's importable set visible here (blendertk for the manifest replay)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def import_fbx(bpy):
    """Import *SRC_FBX* with per-kwarg tolerance across Blender versions.

    ``bpy.ops`` rejects the whole call on one unknown keyword (TypeError), so a
    renamed/removed parameter in a future importer is dropped and the call retried --
    the mirror of the export side's tolerance loop.
    """
    kwargs = {
        "filepath": SRC_FBX,
        "use_custom_props": True,
        "ignore_leaf_bones": True,
        "automatic_bone_orientation": True,
    }
    while True:
        try:
            bpy.ops.import_scene.fbx(**kwargs)
            return
        except TypeError as e:
            match = re.search(r'"(\w+)"', str(e))
            key = match.group(1) if match else None
            if key and key in kwargs:
                print("FBX kwarg skipped (unsupported by this importer): " + key)
                del kwargs[key]
                continue
            raise


def _engine():
    """The blendertk import engine, or None when blendertk is not importable here.

    Reusing it keeps the bake's material rebuild byte-identical to the direct-import
    path instead of maintaining a second copy of that logic in this template.
    """
    try:
        from blendertk.env_utils.maya_bridge._scene_import import MayaSceneImport

        return MayaSceneImport()
    except Exception:
        print("blendertk unavailable in this child; keeping FBX materials:")
        traceback.print_exc()
        return None


def apply_manifest(engine, imported):
    """Replay the conversion's texture sidecar through the shared rebuild engine.

    Best-effort by contract: a bake whose materials stay classic-model is a fidelity
    loss, not a failure, and must never cost the user the linkable .blend.
    """
    manifest = SRC_FBX + ".manifest.json"
    if engine is None or not os.path.isfile(manifest):
        return
    try:
        engine._apply_texture_manifest(manifest, imported)
    except Exception:
        print("Texture-manifest replay failed; keeping FBX materials:")
        traceback.print_exc()


def apply_visibility(engine, imported):
    """Replay the manifest's smart-bake ``visibility`` section through the shared
    engine — FBX carries the visibility curve but Blender's importer drops it, so
    baked (chiefly inherited) visibility reaches the .blend as ``hide_render`` /
    ``hide_viewport`` keys here. Same best-effort contract as the texture replay.
    """
    manifest = SRC_FBX + ".manifest.json"
    if engine is None or not os.path.isfile(manifest):
        return
    try:
        # Default frame_offset (1.0) matches import_fbx's default anim_offset above —
        # keep them in step if that import ever passes a custom anim_offset.
        engine._apply_visibility_manifest(manifest, imported)
    except Exception:
        print("Visibility replay failed; keeping FBX visibility:")
        traceback.print_exc()


def main():
    import bpy

    _extend_sys_path()
    # Empty scene: the factory startup cube/camera/light must not enter the library.
    bpy.ops.wm.read_factory_settings(use_empty=True)
    before = set(bpy.data.objects)
    import_fbx(bpy)
    imported = [o for o in bpy.data.objects if o not in before]
    engine = _engine()
    apply_manifest(engine, imported)
    apply_visibility(engine, imported)
    # relative_remap off: the .blend lives in the cache dir, so relative texture paths
    # would be unresolvable for whoever links it (the absolute-path rule the FBX export
    # already follows).
    bpy.ops.wm.save_as_mainfile(
        filepath=OUT_BLEND, check_existing=False, relative_remap=False, compress=True
    )
    print("Baked {} object(s) into {}".format(len(imported), OUT_BLEND))


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked
# by Blender's default exit-0-after-script-error behavior.
sys.stdout.flush()
os._exit(0)
