# Intermediate -> .blend bake script (foreign-scene reference path). Generated by MayaSceneImport -- do not edit by hand.

"""Import a converted intermediate (USD or FBX) headlessly and save it as a ``.blend`` so a
foreign scene can be LINKED (or opened as a new file).

Blender can only link a ``.blend``, so *referencing* a foreign (Maya) scene needs one hop
more than importing it: the converted intermediate is baked into a cached ``.blend`` here and
the Reference Manager links that. The mirror of mayatk's ``templates/_bake_scene.py`` (which
bakes an intermediate to a cached ``.ma`` for ``cmds.file(reference=True)``).

Everything between the empty scene and the save is ONE engine call,
:meth:`MayaSceneImport.import_payload` -- the same consumer the in-process import and
mayatk's receiving templates run -- so every manifest section (group/locator identity,
textures, visibility, lights, instances, the scene clock) and the key reduction replay the
same way whichever door the scene came through. ``EXTRA_SYS_PATH`` carries blendertk's
and pythontk's roots, then the parent's importable set minus the parent's own interpreter
directories (``HandoffBridge.import_roots`` + ``child_sys_path``), so blendertk is always
importable -- driven from a workspace venv too, whose stdlib must not land ahead of this
Blender's; a child that cannot import it fails the bake rather than caching a degraded
scene.

Progress: each engine step prints a ``pythontk.ProgressRelay`` marker line, flushed, so the
parent's footer follows the bake while it runs (``ScriptRunner`` streams the child's output).

Runs under ``blender --background --factory-startup --python`` via
``pythontk.run_script_to_artifact``, which judges success by the saved ``.blend``, never the
exit code; the exit goes through ``pythontk.ProcessExit.hard_exit`` so the status is honest
and no teardown runs.

The bake starts from an EMPTY factory scene (``read_factory_settings(use_empty=True)``):
the startup cube/camera/light would otherwise land in every linked library.

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

import os
import sys
import traceback

SRC_FILE = r"__SRC_FILE__"
OUT_BLEND = r"__OUT_BLEND__"
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__
# How the dense per-frame keys a conversion carries are reduced before the save: an
# ``AnimUtils.OPTIMIZE_LEVELS`` key, or None to keep every key.
REDUCE_KEYS = __REDUCE_KEYS__


def _extend_sys_path():
    """Make the parent's importable set visible here (blendertk + pythontk)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def main():
    import bpy

    _extend_sys_path()
    import pythontk as ptk
    from blendertk.env_utils.maya_bridge._scene_import import MayaSceneImport

    def progress(done, total, text):
        # One step more than the engine reports: the save below is this script's.
        print(ptk.ProgressRelay.line(done, total + 1, text), flush=True)

    # Empty scene: the factory startup cube/camera/light must not enter the library.
    bpy.ops.wm.read_factory_settings(use_empty=True)
    imported = MayaSceneImport(log_level="INFO").import_payload(
        SRC_FILE, scene_settings=True, reduce_keys=REDUCE_KEYS, progress=progress
    )
    print(ptk.ProgressRelay.line(1, 1, "Saving the .blend"), flush=True)
    # relative_remap off: the .blend lives in the cache dir, so relative texture paths
    # would be unresolvable for whoever links it (the absolute-path rule the FBX export
    # already follows).
    bpy.ops.wm.save_as_mainfile(
        filepath=OUT_BLEND, check_existing=False, relative_remap=False, compress=True
    )
    print("Baked {} object(s) into {}".format(len(imported), OUT_BLEND), flush=True)


def _exit(code):
    """Leave without teardown: ``ProcessExit`` when pythontk imports, else ``os._exit``."""
    sys.stdout.flush()
    sys.stderr.flush()
    try:
        from pythontk.core_utils.process_exit import ProcessExit
    except Exception:  # noqa: BLE001 -- the exit must never raise
        os._exit(code)
    ProcessExit.hard_exit(code)


try:
    main()
except Exception:
    traceback.print_exc()
    _exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked
# by Blender's default exit-0-after-script-error behavior.
_exit(0)
