# Intermediate -> .blend bake script (foreign-scene reference path). Generated by MayaSceneImport -- do not edit by hand.

"""Import a converted intermediate (USD or FBX) headlessly and save it as a ``.blend`` so a
foreign scene can be LINKED.

Blender can only link a ``.blend``, so *referencing* a foreign (Maya) scene needs one hop
more than importing it: the converted intermediate is baked into a cached ``.blend`` here and
the Reference Manager links that. The mirror of mayatk's ``templates/_bake_scene.py`` (which
bakes an intermediate to a cached ``.ma`` for ``cmds.file(reference=True)``).

The source branches on extension. A ``.usd*`` intermediate imports
natively -- materials and visibility need no sidecar -- then ``apply_instances``
rebuilds Maya's instance sets as shared mesh datablocks from the conversion sidecar
(the USD is written flattened so materials survive; USD's own instancing cannot
express Blender linked duplicates). An ``.fbx`` intermediate (the default route, or a
raw ``.fbx`` source) takes the classic path: FBX import + texture/visibility manifest
replay.

Runs under ``blender --background --factory-startup --python`` via
``pythontk.run_script_to_artifact``, which judges success by the saved ``.blend``'s
existence, NOT the exit code (a ``--python`` script that raises does not change Blender's
exit code by default -- the ``os._exit`` below makes it honest).

The bake starts from an EMPTY factory scene (``read_factory_settings(use_empty=True)``):
the startup cube/camera/light would otherwise land in every linked library.

Materials (FBX branch only): FBX carries only the classic model, so the conversion's
``.manifest.json`` sidecar is replayed through the SAME engine the direct-import path uses
(:meth:`MayaSceneImport._apply_texture_manifest`) rather than a second copy of that logic.
``EXTRA_SYS_PATH`` carries the parent Blender's ``sys.path`` into this child (same
Blender, same interpreter -- the entries are valid), so blendertk is normally importable.
When it is not, the bake still succeeds and keeps the FBX-carried materials (logged).

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Blender Python at module scope: no mayatk/blendertk/pythontk imports
# (only Blender's own bundled modules are guaranteed in the child process). blendertk is
# imported *optionally*, inside the manifest step, and its absence is never fatal.
import os
import re
import sys
import traceback

SRC_FILE = r"__SRC_FILE__"
OUT_BLEND = r"__OUT_BLEND__"
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__

USD_EXTENSIONS = (".usd", ".usda", ".usdc", ".usdz")


def _extend_sys_path():
    """Make the parent's importable set visible here (blendertk for the manifest replay)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def _tolerant_op(op, kwargs, label):
    """Call *op* dropping unknown keywords one by one (per-kwarg tolerance).

    ``bpy.ops`` rejects the whole call on one unknown keyword (TypeError), so a
    renamed/removed parameter in a future importer is dropped and the call retried --
    the mirror of the export side's tolerance loop.
    """
    while True:
        try:
            op(**kwargs)
            return
        except TypeError as e:
            match = re.search(r'"(\w+)"', str(e))
            key = match.group(1) if match else None
            if key and key in kwargs and key != "filepath":
                print(label + " kwarg skipped (unsupported by this importer): " + key)
                del kwargs[key]
                continue
            raise


def import_source(bpy):
    """Import *SRC_FILE*, dispatched on its extension (USD native / FBX classic)."""
    if SRC_FILE.lower().endswith(USD_EXTENSIONS):
        # Native defaults, matching the direct-import path (UsdUtils.import_usd).
        _tolerant_op(bpy.ops.wm.usd_import, {"filepath": SRC_FILE}, "USD")
        return
    _tolerant_op(
        bpy.ops.import_scene.fbx,
        {
            "filepath": SRC_FILE,
            "use_custom_props": True,
            "ignore_leaf_bones": True,
            "automatic_bone_orientation": True,
        },
        "FBX",
    )


def _engine():
    """The blendertk import engine, or None when blendertk is not importable here.

    Reusing it keeps the bake's material rebuild byte-identical to the direct-import
    path instead of maintaining a second copy of that logic in this template.
    """
    try:
        from blendertk.env_utils.maya_bridge._scene_import import MayaSceneImport

        return MayaSceneImport()
    except Exception:
        print("blendertk unavailable in this child; keeping FBX materials:")
        traceback.print_exc()
        return None


def apply_manifest(engine, imported):
    """Replay the conversion's texture sidecar through the shared rebuild engine.

    Best-effort by contract: a bake whose materials stay classic-model is a fidelity
    loss, not a failure, and must never cost the user the linkable .blend.
    Never reached by a USD source -- ``main`` routes that to ``apply_instances``.
    """
    manifest = SRC_FILE + ".manifest.json"
    if engine is None or not os.path.isfile(manifest):
        return
    try:
        engine._apply_texture_manifest(manifest, imported)
    except Exception:
        print("Texture-manifest replay failed; keeping FBX materials:")
        traceback.print_exc()


def tag_node_types(engine, imported):
    """Stamp ``maya_node_type`` custom props from the manifest's ``transforms``
    (see the engine method) -- a linked/round-tripped scene keeps enough
    identity to restore Maya groups vs locators exactly on a send back.
    """
    manifest = SRC_FILE + ".manifest.json"
    if engine is None or not os.path.isfile(manifest):
        return
    try:
        engine._tag_maya_node_types(manifest, imported)
    except Exception:
        print("Node-type tagging failed; skipped:")
        traceback.print_exc()


def apply_instances(engine, imported):
    """Rebuild Blender-native linked duplicates from Maya's instance sets.

    USD-source branch only: the USD export flattens instances (that is what
    keeps materials intact), so the relationship travels in the sidecar and is
    replayed through the SAME engine method the direct-import path uses.

    GUARANTEED-OR-FAIL: without the rebuild, a foreign scene OPENED through
    the bake would arrive with every instance as independent geometry -- a
    scene that renders correctly and only betrays itself when an artist edits
    one duplicate and its siblings don't follow. So a present sidecar that
    cannot be replayed (engine unavailable, bad data) raises: main() exits 1
    with NO artifact written, and the parent's judged-by-artifact contract
    reports a failed bake instead of caching a flattened .blend.

    A MISSING sidecar is a hand-fed USD with nothing to replay -- allowed; the
    bridge's own conversions always ship one (v2 contract, enforced upstream
    by bake_scene).
    """
    manifest = SRC_FILE + ".manifest.json"
    if not os.path.isfile(manifest):
        return
    if engine is None:
        raise RuntimeError(
            "blendertk is unavailable in this child (see the traceback above), "
            "so the USD sidecar's instances cannot be rebuilt; refusing to bake "
            "a flattened scene."
        )
    engine._apply_instance_manifest(manifest, imported)


def apply_visibility(engine, imported):
    """Replay the manifest's smart-bake ``visibility`` section through the shared
    engine — FBX carries the visibility curve but Blender's importer drops it, so
    baked (chiefly inherited) visibility reaches the .blend as ``hide_render`` /
    ``hide_viewport`` keys here. Same best-effort contract as the texture replay,
    and likewise never reached by a USD source (USD carries visibility natively).
    """
    manifest = SRC_FILE + ".manifest.json"
    if engine is None or not os.path.isfile(manifest):
        return
    try:
        # Default frame_offset (1.0) matches import_fbx's default anim_offset above —
        # keep them in step if that import ever passes a custom anim_offset.
        engine._apply_visibility_manifest(manifest, imported)
    except Exception:
        print("Visibility replay failed; keeping FBX visibility:")
        traceback.print_exc()


def main():
    import bpy

    _extend_sys_path()
    # Empty scene: the factory startup cube/camera/light must not enter the library.
    bpy.ops.wm.read_factory_settings(use_empty=True)
    before = set(bpy.data.objects)
    import_source(bpy)
    imported = [o for o in bpy.data.objects if o not in before]
    engine = _engine()
    if SRC_FILE.lower().endswith(USD_EXTENSIONS):
        apply_instances(engine, imported)
        # Cosmetic, after the structural work: drop the Empty Blender
        # materializes for the exporter's materials Scope prim ("mtl") so it
        # never enters the linkable library. Never fatal -- clutter is not
        # worth costing the user the .blend.
        if engine is not None:
            try:
                imported = engine._strip_materials_scope(imported, SRC_FILE)
            except Exception:
                print("Materials-scope strip failed (cosmetic; keeping the Empty):")
                traceback.print_exc()
    else:
        tag_node_types(engine, imported)
        apply_manifest(engine, imported)
        apply_visibility(engine, imported)
    # relative_remap off: the .blend lives in the cache dir, so relative texture paths
    # would be unresolvable for whoever links it (the absolute-path rule the FBX export
    # already follows).
    bpy.ops.wm.save_as_mainfile(
        filepath=OUT_BLEND, check_existing=False, relative_remap=False, compress=True
    )
    print("Baked {} object(s) into {}".format(len(imported), OUT_BLEND))


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked
# by Blender's default exit-0-after-script-error behavior.
sys.stdout.flush()
os._exit(0)
