# Maya-scene -> FBX conversion script (Maya -> Blender pull). Generated by MayaSceneImport -- do not edit by hand.

"""Open a Maya scene headlessly (mayapy) and export it as FBX for a Blender import.

The Maya half of ``btk.import_maya_scene``: runs under ``mayapy`` via
``pythontk.run_script_to_artifact``, which judges success by the exported FBX's
existence -- NOT the exit code (standalone teardown is a known crasher, hence the
``os._exit`` below, which skips it entirely).

The scene is opened for conversion only and never saved, so it may be mutated
freely to maximize FBX fidelity: modern surface shaders (standardSurface /
aiStandardSurface / openPBRSurface -- the Maya 2020+ defaults) are translated to
phong before export, because FBX carries only the classic Lambert/Phong material
model and silently drops their textures otherwise (verified empirically: a
standardSurface baseColor file texture arrives in Blender only after translation).

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Maya Python: no mayatk/blendertk imports (the target machine's
# mayapy only has Maya's own modules).
import json
import os
import sys
import traceback

SRC_PATH = r"__SRC_PATH__"
OUT_FBX = r"__OUT_FBX__"
EMBED_TEXTURES = __EMBED_TEXTURES__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__

# Modern surface shaders whose textures FBX cannot carry (classic model only).
MODERN_SHADER_TYPES = ("standardSurface", "aiStandardSurface", "openPBRSurface")
# ShaderFX game shaders: FBX writes them as a "Maya|TEX_*" custom-property set
# that Blender's importer ignores outright ("material link ... ignored").
STINGRAY_SHADER_TYPES = ("StingrayPBS", "ShaderfxShader")
# The StingrayPBS texture slots worth carrying (the env/IBL cubes and BRDF lut
# are renderer plumbing, not material textures).
STINGRAY_TEX_SLOTS = (
    "TEX_color_map", "TEX_normal_map", "TEX_metallic_map",
    "TEX_roughness_map", "TEX_ao_map", "TEX_emissive_map",
)


def _plug_source(cmds, attr):
    """Return the source plug connected into *attr*, or None."""
    try:
        cons = cmds.listConnections(attr, source=True, destination=False, plugs=True)
        return cons[0] if cons else None
    except Exception:
        return None


def _get_first(cmds, node, names, default):
    """First readable attribute value among *names* (attr-name drift across the
    standardSurface family), else *default*."""
    for name in names:
        try:
            value = cmds.getAttr(f"{node}.{name}")
            return value[0] if isinstance(value, list) else value
        except Exception:
            continue
    return default


def _roughness_to_cosine_power(rough):
    return max(2.0, min(100.0, 2.0 / max(rough * rough, 1e-4) - 2.0))


def _translate_surface(cmds, mat, phong):
    """standardSurface family -> phong: re-point maps, approximate scalars."""
    # base color (+map): the channel the user actually noticed missing
    color_src = _plug_source(cmds, f"{mat}.baseColor")
    if color_src:
        cmds.connectAttr(color_src, f"{phong}.color", force=True)
    else:
        c = _get_first(cmds, mat, ("baseColor",), (0.5, 0.5, 0.5))
        w = _get_first(cmds, mat, ("base", "baseWeight"), 1.0)
        cmds.setAttr(f"{phong}.color", c[0] * w, c[1] * w, c[2] * w, type="double3")

    # emission -> incandescence (+map). Gated on the weight: standardSurface's
    # emission weight DEFAULTS to 0, so a stray emissionColor map that emits
    # nothing in Maya must not glow in Blender. Weight clamped to 1 --
    # openPBR's emissionLuminance is in nits and would blow out the color.
    emit_w = min(_get_first(cmds, mat, ("emission", "emissionWeight",
                                        "emissionLuminance"), 0.0), 1.0)
    if emit_w > 0.0:
        emit_src = _plug_source(cmds, f"{mat}.emissionColor")
        if emit_src:
            cmds.connectAttr(emit_src, f"{phong}.incandescence", force=True)
        else:
            e = _get_first(cmds, mat, ("emissionColor",), (0.0, 0.0, 0.0))
            cmds.setAttr(f"{phong}.incandescence", e[0] * emit_w,
                         e[1] * emit_w, e[2] * emit_w, type="double3")

    # normal / bump chain rides as-is
    normal_src = _plug_source(cmds, f"{mat}.normalCamera")
    if normal_src:
        cmds.connectAttr(normal_src, f"{phong}.normalCamera", force=True)

    # specular: color * weight; roughness approximated as cosinePower
    sc = _get_first(cmds, mat, ("specularColor",), (1.0, 1.0, 1.0))
    sw = _get_first(cmds, mat, ("specular", "specularWeight"), 0.0)
    cmds.setAttr(f"{phong}.specularColor", sc[0] * sw, sc[1] * sw, sc[2] * sw,
                 type="double3")
    rough = _get_first(cmds, mat, ("specularRoughness", "roughness"), 0.4)
    cmds.setAttr(f"{phong}.cosinePower", _roughness_to_cosine_power(rough))

    # opacity -> transparency (inverse)
    o = _get_first(cmds, mat, ("opacity",), (1.0, 1.0, 1.0))
    if min(o) < 1.0:
        cmds.setAttr(f"{phong}.transparency", 1.0 - o[0], 1.0 - o[1], 1.0 - o[2],
                     type="double3")


def _translate_stingray(cmds, mat, phong):
    """StingrayPBS (ShaderFX) -> phong: carry color / normal / emissive maps.

    Metallic-workflow maps (metallic / roughness / ao) have no slot in FBX's
    classic material model -- they are dropped, and the conversion log says so.
    ``use_*_map`` toggles are honored (a wired-but-disabled map stays off).
    """
    def use(flag):
        return bool(_get_first(cmds, mat, (flag,), 0))

    color_src = _plug_source(cmds, f"{mat}.TEX_color_map")
    if color_src and use("use_color_map"):
        cmds.connectAttr(color_src, f"{phong}.color", force=True)
    else:
        c = _get_first(cmds, mat, ("base_color",), (0.5, 0.5, 0.5))
        cmds.setAttr(f"{phong}.color", c[0], c[1], c[2], type="double3")

    normal_src = _plug_source(cmds, f"{mat}.TEX_normal_map")
    if normal_src and use("use_normal_map"):
        # Classic-model normal maps ride via a tangent-space bump2d chain.
        file_node = normal_src.split(".")[0]
        bump = cmds.shadingNode("bump2d", asUtility=True, name=f"{mat}_fbxsafe_bump")
        cmds.setAttr(f"{bump}.bumpInterp", 1)  # tangent-space normals
        try:
            cmds.connectAttr(f"{file_node}.outAlpha", f"{bump}.bumpValue", force=True)
        except Exception:
            pass  # non-file source; the exporter still reads the chain's texture
        cmds.connectAttr(f"{bump}.outNormal", f"{phong}.normalCamera", force=True)

    # Gated on intensity like the standardSurface emission weight: a wired map
    # with intensity 0 emits nothing in Maya and must not glow in Blender.
    # (Unreadable intensity — a ShaderFX variant — defaults to letting the map ride.)
    emis_src = _plug_source(cmds, f"{mat}.TEX_emissive_map")
    if (emis_src and use("use_emissive_map")
            and _get_first(cmds, mat, ("emissive_intensity",), 1.0) > 0.0):
        cmds.connectAttr(emis_src, f"{phong}.incandescence", force=True)

    rough = _get_first(cmds, mat, ("roughness",), 0.4)
    cmds.setAttr(f"{phong}.cosinePower", _roughness_to_cosine_power(rough))

    dropped = [name for name in ("metallic", "roughness", "ao")
               if _plug_source(cmds, f"{mat}.TEX_{name}_map")]
    if dropped:
        print(f"{mat}: no classic-FBX slot for {', '.join(dropped)} map(s) -- not carried")


def _resolve_workspace(cmds, scene_path):
    """Open the Maya project owning *scene_path* (nearest workspace.mel above it).

    Without it, headless Maya cannot resolve project-relative texture paths
    (``sourceimages/...``): the FBX then carries unresolvable strings (pink
    materials in Blender -- Blender's image search only looks near the FBX,
    which sits in the temp dir) and the manifest collects no files. Returns the
    project root, or None when the scene lives outside any project.
    """
    directory = os.path.dirname(os.path.abspath(scene_path))
    while True:
        if os.path.isfile(os.path.join(directory, "workspace.mel")):
            try:
                cmds.workspace(directory, openWorkspace=True)
                return directory
            except Exception:
                return None
        parent = os.path.dirname(directory)
        if parent == directory:
            return None
        directory = parent


def _resolved_file(cmds, file_node):
    """Absolute path of a file node's texture, workspace-resolved; None if absent."""
    try:
        path = cmds.getAttr(f"{file_node}.fileTextureName")
    except Exception:
        return None
    if not path:
        return None
    if not os.path.isfile(path):
        try:
            expanded = cmds.workspace(expandName=path)
            if os.path.isfile(expanded):
                path = expanded
        except Exception:
            pass
    return os.path.abspath(path) if os.path.isfile(path) else None


def _material_files(cmds, mat, node_type):
    """The texture files feeding *mat* -- the payload FBX cannot carry.

    Stingray reads its declared TEX_* slots (history would drag in the env/BRDF
    plumbing); the surface family walks history (user-built networks are free-form).
    """
    files = []
    if node_type in STINGRAY_SHADER_TYPES:
        for slot in STINGRAY_TEX_SLOTS:
            src = _plug_source(cmds, f"{mat}.{slot}")
            if src:
                path = _resolved_file(cmds, src.split(".")[0])
                if path:
                    files.append(path)
    else:
        for node in cmds.listHistory(mat) or []:
            try:
                if cmds.nodeType(node) == "file":
                    path = _resolved_file(cmds, node)
                    if path:
                        files.append(path)
            except Exception:
                continue
    return sorted(set(files), key=files.index)


def _sg_member_names(cmds, sg):
    """Short transform names assigned to *sg* (namespace/path stripped -- what the
    FBX-imported Blender objects will be named after)."""
    names = []
    for member in cmds.sets(sg, query=True) or []:
        node = member.split(".")[0]
        try:
            if cmds.nodeType(node) != "transform":
                parents = cmds.listRelatives(node, parent=True) or []
                node = parents[0] if parents else node
        except Exception:
            pass
        short = node.split("|")[-1].split(":")[-1]
        if short not in names:
            names.append(short)
    return names


def fbx_safe_materials(cmds):
    """Swap every FBX-hostile shader for an equivalent phong on its shading group.

    Texture connections are re-pointed, scalar values approximated. Per-material
    failures degrade to the untranslated shader (gray in Blender) rather than
    aborting the conversion. The scene is throwaway -- nothing is restored.

    ONE phong per source material: production scenes routinely feed one material
    into many shading groups (per-object SG splits, merged imports), and a
    per-SG translation explodes into "_fbxsafe1..N" duplicates. Every SG of an
    already-translated material reuses its phong, and the manifest entry merges
    the member objects.

    Returns manifest entries for the translated materials: the original texture
    files (packed metallic/roughness/ao maps included -- FBX's classic model has
    no slot for them) so the Blender side can rebuild the material natively.
    """
    entries = []
    translated = {}  # source material -> (phong, entry)
    for sg in cmds.ls(type="shadingEngine") or []:
        try:
            src = _plug_source(cmds, f"{sg}.surfaceShader")
            if not src:
                continue
            mat = src.split(".")[0]
            if mat in translated:
                phong, entry = translated[mat]
                cmds.connectAttr(f"{phong}.outColor", f"{sg}.surfaceShader", force=True)
                for member in _sg_member_names(cmds, sg):
                    if member not in entry["objects"]:
                        entry["objects"].append(member)
                continue
            node_type = cmds.nodeType(mat)
            if node_type in MODERN_SHADER_TYPES:
                translate = _translate_surface
            elif node_type in STINGRAY_SHADER_TYPES:
                translate = _translate_stingray
            else:
                continue
            phong = cmds.shadingNode("phong", asShader=True, name=f"{mat}_fbxsafe")
            translate(cmds, mat, phong)
            cmds.connectAttr(f"{phong}.outColor", f"{sg}.surfaceShader", force=True)
            entry = {
                "name": mat.split(":")[-1],
                "shader_type": node_type,
                "fbx_material": phong,
                "objects": _sg_member_names(cmds, sg),
                "files": _material_files(cmds, mat, node_type),
            }
            entries.append(entry)
            translated[mat] = (phong, entry)
            print(
                "fbx-safe: {} -> {} ({} texture file(s) resolved)".format(
                    mat, phong, len(entry["files"])
                )
            )
        except Exception:
            print(f"fbx-safe translation skipped for {sg}:")
            traceback.print_exc()
    return entries


def write_texture_manifest(entries, path):
    """Sidecar for the textures FBX cannot carry, consumed by MayaSceneImport.

    File-less entries are written too: a translated material whose texture
    paths never resolved must surface as a NAMED warning on the Blender side,
    not as silently pink geometry (live production report).
    """
    if not entries:
        return
    with open(path, "w", encoding="utf-8") as fh:
        json.dump({"version": 1, "materials": entries}, fh, indent=1)


def main():
    import maya.standalone

    maya.standalone.initialize(name="python")
    import maya.cmds as cmds
    import maya.mel as mel

    workspace = _resolve_workspace(cmds, SRC_PATH)
    print("workspace: " + (workspace or "none found (Maya fallback resolution only)"))
    cmds.file(
        SRC_PATH, open=True, force=True, ignoreVersion=True, loadReferenceDepth="all"
    )
    manifest_entries = fbx_safe_materials(cmds)

    if not cmds.pluginInfo("fbxmaya", query=True, loaded=True):
        cmds.loadPlugin("fbxmaya")

    mel.eval("FBXResetExport")  # never inherit whatever preset state this install has
    # Full-fidelity battery -- everything that can ride in the FBX does (mirrors
    # mayatk's established export set, with cameras/lights ON: this is a whole-
    # scene import, not an asset export). Per-flag tolerance: an FBX plugin
    # version missing one command must not kill the conversion.
    for flag in (
        "FBXExportSmoothingGroups -v true",
        # All-hard dense meshes hang the exporter with HardEdges on -- keep it off.
        "FBXExportHardEdges -v false",
        "FBXExportSmoothMesh -v true",
        "FBXExportTangents -v true",
        "FBXExportInstances -v true",
        "FBXExportSkins -v true",
        "FBXExportShapes -v true",
        "FBXExportSkeletonDefinitions -v true",
        "FBXExportCameras -v true",
        "FBXExportLights -v true",
        "FBXExportInputConnections -v true",
        "FBXExportEmbeddedTextures -v " + ("true" if EMBED_TEXTURES else "false"),
        "FBXExportBakeComplexAnimation -v "
        + ("true" if INCLUDE_ANIMATION else "false"),
    ):
        try:
            mel.eval(flag)
        except Exception:
            print("FBX flag skipped (unsupported by this plugin): " + flag)
    mel.eval('FBXExport -f "{}"'.format(OUT_FBX))
    # Written only after a successful export (a manifest implies its FBX).
    write_texture_manifest(manifest_entries, OUT_FBX + ".manifest.json")


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; skip standalone teardown (known access violations).
sys.stdout.flush()
os._exit(0)
