# Maya-scene -> USD conversion script (Maya -> Blender pull). Generated by MayaSceneImport -- do not edit by hand.

"""Open a Maya scene headlessly (mayapy) and export it as USD for a Blender import.

The USD sibling of ``templates/_import_scene.py`` (the FBX route), selected via
``import_scene(via="usd")``. Runs under ``mayapy`` via
``pythontk.run_script_to_artifact``, which judges success by the exported USD's
existence -- NOT the exit code (standalone teardown is a known crasher, hence the
``os._exit`` below).

Where the FBX route must downgrade every modern shader to phong and sidecar the
PBR textures in a ``.manifest.json``, USD needs neither: ``mayaUSDExport``'s
registry shading converts the standardSurface family to ``UsdPreviewSurface``
natively (metallic / roughness / normal / emissive textures included), which
Blender's importer wires straight into a Principled BSDF. The one translation
still needed is the ShaderFX game-shader family (StingrayPBS) -- the registry
has no exporter for it -- which is swapped for an equivalent ``standardSurface``
so even its packed metallic map gets a real USD slot (the FBX route can only
carry that via the manifest rebuild).

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Maya Python: no mayatk/blendertk imports (the target machine's
# mayapy only has Maya's own modules).
import os
import re
import sys
import traceback

SRC_PATH = r"__SRC_PATH__"
OUT_USD = r"__OUT_USD__"
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__

# ShaderFX game shaders: the mayaUsd registry has no exporter for them (they
# would arrive as displayColor-only). Translated to standardSurface below.
STINGRAY_SHADER_TYPES = ("StingrayPBS", "ShaderfxShader")


def _plug_source(cmds, attr):
    """Return the source plug connected into *attr*, or None."""
    try:
        cons = cmds.listConnections(attr, source=True, destination=False, plugs=True)
        return cons[0] if cons else None
    except Exception:
        return None


def _get_first(cmds, node, names, default):
    """First readable attribute value among *names*, else *default*."""
    for name in names:
        try:
            value = cmds.getAttr(f"{node}.{name}")
            return value[0] if isinstance(value, list) else value
        except Exception:
            continue
    return default


def _resolve_workspace(cmds, scene_path):
    """Open the Maya project owning *scene_path* (nearest workspace.mel above it).

    Without it, headless Maya cannot resolve project-relative texture paths
    (``sourceimages/...``) and the USD would carry unresolvable asset refs --
    the same pink-materials failure the FBX route fixed this way.
    """
    directory = os.path.dirname(os.path.abspath(scene_path))
    while True:
        if os.path.isfile(os.path.join(directory, "workspace.mel")):
            try:
                cmds.workspace(directory, openWorkspace=True)
                return directory
            except Exception:
                return None
        parent = os.path.dirname(directory)
        if parent == directory:
            return None
        directory = parent


def _translate_stingray_to_ss(cmds, mat, ss):
    """StingrayPBS -> standardSurface: every PBR slot gets a NATIVE USD home.

    Unlike the FBX route's phong downgrade, metallic and roughness maps ride
    as real UsdPreviewSurface inputs (single-channel reads via ``outColorR``
    / ``outAlpha``). ``use_*_map`` toggles are honored. AO has no
    standardSurface slot and is dropped with a note.
    """
    def use(flag):
        return bool(_get_first(cmds, mat, (flag,), 0))

    color_src = _plug_source(cmds, f"{mat}.TEX_color_map")
    if color_src and use("use_color_map"):
        cmds.connectAttr(color_src, f"{ss}.baseColor", force=True)
    else:
        c = _get_first(cmds, mat, ("base_color",), (0.5, 0.5, 0.5))
        cmds.setAttr(f"{ss}.baseColor", c[0], c[1], c[2], type="double3")

    normal_src = _plug_source(cmds, f"{mat}.TEX_normal_map")
    if normal_src and use("use_normal_map"):
        # Tangent-space bump2d chain -- the pattern the registry exporter
        # recognizes and writes as a UsdUVTexture normal input.
        file_node = normal_src.split(".")[0]
        bump = cmds.shadingNode("bump2d", asUtility=True, name=f"{mat}_usdsafe_bump")
        cmds.setAttr(f"{bump}.bumpInterp", 1)  # tangent-space normals
        try:
            cmds.connectAttr(f"{file_node}.outAlpha", f"{bump}.bumpValue", force=True)
        except Exception:
            pass
        cmds.connectAttr(f"{bump}.outNormal", f"{ss}.normalCamera", force=True)

    metal_src = _plug_source(cmds, f"{mat}.TEX_metallic_map")
    if metal_src and use("use_metallic_map"):
        file_node = metal_src.split(".")[0]
        cmds.connectAttr(f"{file_node}.outColorR", f"{ss}.metalness", force=True)
    else:
        cmds.setAttr(f"{ss}.metalness", _get_first(cmds, mat, ("metallic",), 0.0))

    rough_src = _plug_source(cmds, f"{mat}.TEX_roughness_map")
    if rough_src and use("use_roughness_map"):
        file_node = rough_src.split(".")[0]
        cmds.connectAttr(
            f"{file_node}.outColorR", f"{ss}.specularRoughness", force=True
        )
    else:
        cmds.setAttr(
            f"{ss}.specularRoughness", _get_first(cmds, mat, ("roughness",), 0.4)
        )

    # Gated on intensity like the FBX route: a wired map with intensity 0
    # emits nothing in Maya and must not glow in Blender.
    emis_src = _plug_source(cmds, f"{mat}.TEX_emissive_map")
    if (emis_src and use("use_emissive_map")
            and _get_first(cmds, mat, ("emissive_intensity",), 1.0) > 0.0):
        cmds.connectAttr(emis_src, f"{ss}.emissionColor", force=True)
        cmds.setAttr(f"{ss}.emission", 1.0)

    if _plug_source(cmds, f"{mat}.TEX_ao_map"):
        print(f"{mat}: standardSurface has no AO slot -- ao map not carried")


def usd_safe_materials(cmds):
    """Swap ShaderFX game shaders for standardSurface on their shading groups.

    ONE standardSurface per source material (the FBX route's memoization rule:
    per-SG translation explodes into duplicates on production scenes). The
    scene is throwaway -- nothing is restored. The standardSurface family
    itself passes through untouched (the registry exports it natively).
    """
    translated = {}
    for sg in cmds.ls(type="shadingEngine") or []:
        try:
            src = _plug_source(cmds, f"{sg}.surfaceShader")
            if not src:
                continue
            mat = src.split(".")[0]
            if mat in translated:
                cmds.connectAttr(
                    f"{translated[mat]}.outColor", f"{sg}.surfaceShader", force=True
                )
                continue
            if cmds.nodeType(mat) not in STINGRAY_SHADER_TYPES:
                continue
            ss = cmds.shadingNode(
                "standardSurface", asShader=True, name=f"{mat}_usdsafe"
            )
            _translate_stingray_to_ss(cmds, mat, ss)
            cmds.connectAttr(f"{ss}.outColor", f"{sg}.surfaceShader", force=True)
            translated[mat] = ss
            print(f"usd-safe: {mat} -> {ss}")
        except Exception:
            print(f"usd-safe translation skipped for {sg}:")
            traceback.print_exc()


def export_usd(cmds):
    """Whole-scene ``mayaUSDExport`` with per-flag tolerance across mayaUsd versions.

    ``cmds`` rejects the whole call on one unknown flag (TypeError), so a flag
    this mayaUsd doesn't know is dropped and the call retried -- the mirror of
    the FBX template's per-flag MEL tolerance. ``defaultMeshScheme='none'`` is
    load-bearing: the exporter defaults to catmullClark, which Blender would
    then subdivide-smooth meshes Maya displayed as plain polys.
    """
    kwargs = {
        "file": OUT_USD,
        "shadingMode": "useRegistry",
        "convertMaterialsTo": ["UsdPreviewSurface"],
        "exportInstances": True,
        "mergeTransformAndShape": True,
        "exportUVs": True,
        "exportVisibility": True,
        "exportBlendShapes": True,
        "exportSkels": "auto",
        "exportSkin": "auto",
        "defaultMeshScheme": "none",
        # The USD lives in the temp dir; relative asset refs would be
        # unresolvable in Blender (the FBX route's path_mode=ABSOLUTE mirror).
        "exportRelativeTextures": "absolute",
    }
    if INCLUDE_ANIMATION:
        start = cmds.playbackOptions(query=True, animationStartTime=True)
        end = cmds.playbackOptions(query=True, animationEndTime=True)
        kwargs["frameRange"] = (start, end)
    while True:
        try:
            cmds.mayaUSDExport(**kwargs)
            return
        except TypeError as e:
            match = re.search(r"'(\w+)'", str(e))
            key = match.group(1) if match else None
            if key and key in kwargs and key != "file":
                print("USD flag skipped (unsupported by this mayaUsd): " + key)
                del kwargs[key]
                continue
            raise


def main():
    import maya.standalone

    maya.standalone.initialize(name="python")
    import maya.cmds as cmds

    workspace = _resolve_workspace(cmds, SRC_PATH)
    print("workspace: " + (workspace or "none found (Maya fallback resolution only)"))
    cmds.file(
        SRC_PATH, open=True, force=True, ignoreVersion=True, loadReferenceDepth="all"
    )
    usd_safe_materials(cmds)
    if not cmds.pluginInfo("mayaUsdPlugin", query=True, loaded=True):
        cmds.loadPlugin("mayaUsdPlugin")
    export_usd(cmds)


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; skip standalone teardown (known access violations).
sys.stdout.flush()
os._exit(0)
