# Maya-scene -> USD conversion script (Maya -> Blender pull). Generated by MayaSceneImport -- do not edit by hand.

"""Open a Maya scene headlessly (mayapy) and export it as USD for a Blender import.

The USD sibling of ``templates/_import_scene.py`` (the FBX route), selected via
``import_scene(via="usd")``. Runs under ``mayapy`` via
``pythontk.run_script_to_artifact``, which judges success by the exported USD's
existence -- NOT the exit code (standalone teardown is a known crasher, hence the
``os._exit`` below).

Where the FBX route must downgrade every modern shader to phong and sidecar the
PBR textures in a ``.manifest.json``, USD needs neither: ``mayaUSDExport``'s
registry shading converts the standardSurface family to ``UsdPreviewSurface``
natively (metallic / roughness / normal / emissive textures included), which
Blender's importer wires straight into a Principled BSDF. The one translation
still needed is the ShaderFX game-shader family (StingrayPBS) -- the registry
has no exporter for it -- which is swapped for an equivalent ``standardSurface``
so even its packed metallic map gets a real USD slot (the FBX route can only
carry that via the manifest rebuild).

Skin pre-pass (optional): a skinCluster whose influences span more than one
root joint gets NO skin from mayaUsd's exporter (its points are baked instead) --
see ``_export_ready_skins``, which hands mayatk's ``SkinUtils.flatten_influences``
the frames this export samples; guarded, like the FBX route's smart bake.

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Maya Python by default: the core conversion imports only Maya's
# own modules. The OPTIONAL skin pre-pass imports mayatk, but behind a guard
# (missing -> the export proceeds as authored), so this template still runs on a
# bare mayapy.
import math
import os
import re
import sys
import traceback

SRC_PATH = r"__SRC_PATH__"
OUT_USD = r"__OUT_USD__"
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__
# "rig" carries the rig logic as a RigGraph planned against the CONSUMER's
# capability (sent in as RIG_CAPABILITY, a JSON string); only what the plan
# cannot build is baked -- the USD route samples the rest natively. Schema 15.
RIG_MODE = __RIG_MODE__
RIG_CAPABILITY = __RIG_CAPABILITY__

# ShaderFX game shaders: the mayaUsd registry has no exporter for them (they
# would arrive as displayColor-only). Translated to standardSurface below.
STINGRAY_SHADER_TYPES = ("StingrayPBS", "ShaderfxShader")
# The StingrayPBS texture slots worth carrying (the env/IBL cubes and BRDF lut
# are renderer plumbing, not material textures).
STINGRAY_TEX_SLOTS = (
    "TEX_color_map",
    "TEX_normal_map",
    "TEX_metallic_map",
    "TEX_roughness_map",
    "TEX_ao_map",
    "TEX_emissive_map",
)
# Stingray slot -> the logical channel vocabulary the manifest speaks (the same
# names mtk's MatManifest emits, resolved Blender-side through
# ptk.MapRegistry.resolve_type_from_channel). Lets the applier rebuild a texture
# whose FILENAME carries no map-type token -- a plain color map named after a
# product would otherwise be unclassifiable. Spelled out rather than imported:
# this template is dependency-free by contract.
STINGRAY_SLOT_CHANNELS = {
    "TEX_color_map": "baseColor",
    "TEX_normal_map": "normal",
    "TEX_metallic_map": "metallic",
    "TEX_roughness_map": "roughness",
    "TEX_ao_map": "ambientOcclusion",
    "TEX_emissive_map": "emission",
}
# Stingray slots that hold DATA, not color: their file nodes get a raw color
# space for the export so the UsdUVTexture says so (Blender reads it as
# Non-Color; a normal map tagged sRGB shades wrong).
STINGRAY_DATA_SLOTS = (
    "TEX_normal_map",
    "TEX_metallic_map",
    "TEX_roughness_map",
    "TEX_ao_map",
)


def _ns_safe(name):
    """*name* with namespace colons flattened (``ns:mat`` -> ``ns_mat``) -- nodes
    we CREATE live at the root namespace under a colon-free name (the FBX
    template's rule; referenced scenes arrive namespaced)."""
    return name.replace(":", "_")


def _plug_source(cmds, attr):
    """Return the source plug connected into *attr*, or None."""
    try:
        cons = cmds.listConnections(attr, source=True, destination=False, plugs=True)
        return cons[0] if cons else None
    except Exception:
        return None


def _get_first(cmds, node, names, default):
    """First readable attribute value among *names*, else *default*."""
    for name in names:
        try:
            value = cmds.getAttr(f"{node}.{name}")
            return value[0] if isinstance(value, list) else value
        except Exception:
            continue
    return default


def _resolve_workspace(cmds, scene_path):
    """Open the Maya project owning *scene_path* (nearest workspace.mel above it).

    Without it, headless Maya cannot resolve project-relative texture paths
    (``sourceimages/...``) and the USD would carry unresolvable asset refs --
    the same pink-materials failure the FBX route fixed this way.
    """
    directory = os.path.dirname(os.path.abspath(scene_path))
    while True:
        if os.path.isfile(os.path.join(directory, "workspace.mel")):
            try:
                cmds.workspace(directory, openWorkspace=True)
                return directory
            except Exception:
                return None
        parent = os.path.dirname(directory)
        if parent == directory:
            return None
        directory = parent


def _open_scene(cmds, path):
    """Open *path*, tolerating the RuntimeError noise of a scene that LOADED but
    reported errors -- missing renderer plugins, unknown nodes (routine for
    production scenes on a vanilla mayapy; the FBX template's rule). A failed
    open -- nothing loaded -- still raises."""
    try:
        cmds.file(
            path, open=True, force=True, ignoreVersion=True, loadReferenceDepth="all"
        )
    except RuntimeError as error:
        opened = cmds.file(query=True, sceneName=True) or ""
        if os.path.normcase(os.path.abspath(opened)) != os.path.normcase(
            os.path.abspath(path)
        ):
            raise
        print("scene opened with load errors (tolerated): {}".format(error))


def _translate_stingray_to_ss(cmds, mat, ss):
    """StingrayPBS -> standardSurface: every PBR slot gets a NATIVE USD home.

    Unlike the FBX route's phong downgrade, metallic and roughness maps ride
    as real UsdPreviewSurface inputs (single-channel reads via ``outColorR``
    / ``outAlpha``). ``use_*_map`` toggles are honored. AO has no
    standardSurface slot and is dropped with a note.
    """

    def use(flag):
        return bool(_get_first(cmds, mat, (flag,), 0))

    color_src = _plug_source(cmds, f"{mat}.TEX_color_map")
    if color_src and use("use_color_map"):
        cmds.connectAttr(color_src, f"{ss}.baseColor", force=True)
    else:
        c = _get_first(cmds, mat, ("base_color",), (0.5, 0.5, 0.5))
        cmds.setAttr(f"{ss}.baseColor", c[0], c[1], c[2], type="double3")

    normal_src = _plug_source(cmds, f"{mat}.TEX_normal_map")
    if normal_src and use("use_normal_map"):
        # The file's outColor STRAIGHT into normalCamera: the only wiring mayaUsd
        # 0.30's registry exporter writes as UsdPreviewSurface.normal (probed --
        # a bump2d chain, tangent-space or not, and aiNormalMap export as a
        # dangling UsdUVTexture with normal=None).
        file_node = normal_src.split(".")[0]
        cmds.connectAttr(f"{file_node}.outColor", f"{ss}.normalCamera", force=True)
    for slot in STINGRAY_DATA_SLOTS:
        src = _plug_source(cmds, f"{mat}.{slot}")
        if src:
            try:
                cmds.setAttr(f"{src.split('.')[0]}.colorSpace", "Raw", type="string")
            except Exception:
                pass

    metal_src = _plug_source(cmds, f"{mat}.TEX_metallic_map")
    if metal_src and use("use_metallic_map"):
        file_node = metal_src.split(".")[0]
        cmds.connectAttr(f"{file_node}.outColorR", f"{ss}.metalness", force=True)
    else:
        cmds.setAttr(f"{ss}.metalness", _get_first(cmds, mat, ("metallic",), 0.0))

    rough_src = _plug_source(cmds, f"{mat}.TEX_roughness_map")
    if rough_src and use("use_roughness_map"):
        file_node = rough_src.split(".")[0]
        cmds.connectAttr(
            f"{file_node}.outColorR", f"{ss}.specularRoughness", force=True
        )
    else:
        cmds.setAttr(
            f"{ss}.specularRoughness", _get_first(cmds, mat, ("roughness",), 0.4)
        )

    # Gated on intensity like the FBX route: a wired map with intensity 0
    # emits nothing in Maya and must not glow in Blender.
    emis_src = _plug_source(cmds, f"{mat}.TEX_emissive_map")
    if (
        emis_src
        and use("use_emissive_map")
        and _get_first(cmds, mat, ("emissive_intensity",), 1.0) > 0.0
    ):
        cmds.connectAttr(emis_src, f"{ss}.emissionColor", force=True)
        cmds.setAttr(f"{ss}.emission", 1.0)

    if _plug_source(cmds, f"{mat}.TEX_ao_map"):
        print(f"{mat}: standardSurface has no AO slot -- ao map not carried")


def _flatten_normal_chain(cmds, mat):
    """Re-wire a tangent-space ``bump2d`` normal chain on *mat* into the direct
    ``file.outColor -> normalCamera`` connection mayaUsd 0.30 exports as
    ``UsdPreviewSurface.normal`` (a bump2d chain exports as normal=None -- probed).
    The conversion scene is throwaway, so the chain is simply bypassed."""
    src = _plug_source(cmds, f"{mat}.normalCamera")
    if not src:
        return
    node = src.split(".")[0]
    try:
        if cmds.nodeType(node) != "bump2d" or cmds.getAttr(f"{node}.bumpInterp") != 1:
            return
        upstream = _plug_source(cmds, f"{node}.bumpValue")
        if not upstream or cmds.nodeType(upstream.split(".")[0]) != "file":
            return
        file_node = upstream.split(".")[0]
        cmds.connectAttr(f"{file_node}.outColor", f"{mat}.normalCamera", force=True)
        cmds.setAttr(f"{file_node}.colorSpace", "Raw", type="string")
        print(f"usd-safe: {mat} normal map wired directly (bump2d bypassed)")
    except Exception:
        print(f"usd-safe: normal chain on {mat} left as is:")
        traceback.print_exc()


def usd_safe_materials(cmds):
    """Make every material export as well as mayaUsd's registry can write it.

    ShaderFX game shaders are swapped for standardSurface on their shading groups
    -- ONE standardSurface per source material (the FBX route's memoization rule:
    per-SG translation explodes into duplicates on production scenes). The
    standardSurface family passes through, except that a tangent-space bump2d
    normal chain is bypassed (:func:`_flatten_normal_chain`). The scene is
    throwaway -- nothing is restored. What the registry still cannot express
    (packed maps, AO, anything it drops) rides the manifest instead
    (:func:`collect_materials`) and is rebuilt Blender-side, exactly as on the
    FBX route.
    """
    translated = {}
    for sg in cmds.ls(type="shadingEngine") or []:
        try:
            src = _plug_source(cmds, f"{sg}.surfaceShader")
            if not src:
                continue
            mat = src.split(".")[0]
            if mat in translated:
                cmds.connectAttr(
                    f"{translated[mat]}.outColor", f"{sg}.surfaceShader", force=True
                )
                continue
            if cmds.nodeType(mat) not in STINGRAY_SHADER_TYPES:
                _flatten_normal_chain(cmds, mat)
                continue
            ss = cmds.shadingNode(
                "standardSurface", asShader=True, name=f"{_ns_safe(mat)}_usdsafe"
            )
            _translate_stingray_to_ss(cmds, mat, ss)
            cmds.connectAttr(f"{ss}.outColor", f"{sg}.surfaceShader", force=True)
            translated[mat] = ss
            print(f"usd-safe: {mat} -> {ss}")
        except Exception:
            print(f"usd-safe translation skipped for {sg}:")
            traceback.print_exc()


# Drivers that move things WITHOUT keys of their own: their motion cannot be
# inferred from key times, so they force the full playback range.
_UNKEYED_DRIVERS = (
    "parentConstraint",
    "pointConstraint",
    "orientConstraint",
    "scaleConstraint",
    "aimConstraint",
    "poleVectorConstraint",
    "geometryConstraint",
    "normalConstraint",
    "tangentConstraint",
    "expression",
    "ikHandle",
    "motionPath",
)


def _animation_frame_range(cmds):
    """The frames actually worth sampling, or ``None`` for a static export.

    USD has no animation *curves* -- ``frameRange`` makes mayaUSDExport write a
    time sample per frame for EVERY prim, so the range is a direct multiplier on
    export cost (measured on a 755-mesh production module with a 1-200 playback
    range: 234s with the full range vs 1.8s static, byte-identical result).

    So sample only what moves:
      * nothing animated                -> ``None``  (static export)
      * unkeyed drivers present         -> the full playback range (their motion
                                           can't be derived from key times)
      * plain keyframes only            -> the keys' own span, clamped to the
                                           playback range (a stray far-out key
                                           must not multiply the sample count,
                                           and frames outside the scene's own
                                           time are not what the user sees)

    Only TIME-based curves (``animCurveT*``) count: ``animCurveU*`` are
    set-driven keys whose "times" are driver *values*, not frames -- their
    motion over time comes from whatever animates the driver, which is itself a
    time curve.
    """
    playback = (
        cmds.playbackOptions(query=True, animationStartTime=True),
        cmds.playbackOptions(query=True, animationEndTime=True),
    )
    if cmds.ls(type=_UNKEYED_DRIVERS):
        return playback

    curves = (
        cmds.ls(type=("animCurveTA", "animCurveTL", "animCurveTU", "animCurveTT")) or []
    )
    if not curves:
        return None
    # ONE query for every curve -- per-curve calls cost a round trip each, and a
    # rigged scene carries thousands.
    times = cmds.keyframe(curves, query=True, timeChange=True) or []
    if not times:
        return None

    # floor/ceil, not int(): int() truncates toward zero, which would clip a key
    # at 20.5 down to 20 (losing motion) and mis-round negative frames.
    start = max(playback[0], math.floor(min(times)))
    end = min(playback[1], math.ceil(max(times)))
    if end < start:  # keys live entirely outside the scene's own time
        return None
    return (start, end)


def export_usd(cmds, frame_range=None):
    """Whole-scene ``mayaUSDExport`` with per-flag tolerance across mayaUsd versions.

    ``cmds`` rejects the whole call on one unknown flag (TypeError), so a flag
    this mayaUsd doesn't know is dropped and the call retried -- the mirror of
    the FBX template's per-flag MEL tolerance. ``defaultMeshScheme='none'`` is
    load-bearing: the exporter defaults to catmullClark, which Blender would
    then subdivide-smooth meshes Maya displayed as plain polys.
    """
    # These flags ARE ``UsdUtils.INTERCHANGE_EXPORT_OPTIONS`` -- the shared hand-off
    # set mayatk adopted FROM this route, reason by measured reason. Drift-guarded
    # against it by
    # ``mayatk/test/test_blender_bridge.py::TestPullTemplateCopiesMatchTheirSource``.
    kwargs = {
        "file": OUT_USD,
        "shadingMode": "useRegistry",
        "convertMaterialsTo": ["UsdPreviewSurface"],
        # exportInstances is DELIBERATELY off (measured on Maya 2025 / mayaUsd).
        # When the scene holds instanced shapes, material export degrades badly
        # and can collapse outright: on a probe scene whose only instances were
        # two cubes, `def Material` went 3 -> 0 and `material:binding` 4 -> 0
        # with the flag on -- taking `mat_solo`, bound ONLY to a non-instanced
        # mesh, with it. (On other scenes only the instanced prims lose their
        # binding; either way objects arrive unshaded.) It also lands geometry
        # in a `prototypes` collection of collection-instance Empties, which a
        # pull-for-editing user cannot edit per-object, and drops per-instance
        # material assignments, since all instances share one prototype.
        # Flattening does NOT mean losing instances. USD's own instancing model
        # cannot give Blender what production needs -- measured both ways: the
        # importer turns instanceable prims into collection-instance Empties
        # under a `prototypes` collection (uneditable), and disabling that
        # (`support_scene_instancing=False`) yields real objects with ZERO data
        # sharing. Neither is Blender's linked-duplicate model. So the export
        # flattens (materials + clean structure), `collect_instance_groups`
        # records the relationship in the sidecar, and the Blender side rebuilds
        # native shared mesh datablocks from it -- PROPS_RF lands at 628
        # datablocks for 755 objects, matching the FBX route's 627.
        # Pinned by the e2e's e2e_inst_* trap.
        "exportInstances": False,
        "mergeTransformAndShape": True,
        "exportUVs": True,
        "exportVisibility": True,
        "exportBlendShapes": True,
        "exportSkels": "auto",
        "exportSkin": "auto",
        "defaultMeshScheme": "none",
        # The USD lives in the temp dir; relative asset refs would be
        # unresolvable in Blender (the FBX route's path_mode=ABSOLUTE mirror).
        "exportRelativeTextures": "absolute",
        # The default materials-scope placement DROPS EVERY MATERIAL when a root
        # is namespaced -- a referenced asset, the production norm ("Cannot
        # append child 'mtl' to path ''", mayaUsd 0.30, probed). Legacy keeps them.
        "legacyMaterialScope": True,
        # The exporter's default rewrites ``map1`` to ``st``, and USD stores
        # primvars alphabetically -- a second set (``lightmap``) sorts ahead
        # and Blender's importer would make IT the active map. ``map1`` by
        # name is what the Blender side activates (the FBX route's spelling).
        "preserveUVSetNames": True,
    }
    if frame_range:
        kwargs["frameRange"] = frame_range
        print("USD export: sampling frames {}-{}".format(*frame_range))
    else:
        print("USD export: no animation to sample -- static export (no frameRange)")
    while True:
        try:
            cmds.mayaUSDExport(**kwargs)
            return
        except TypeError as e:
            match = re.search(r"'(\w+)'", str(e))
            key = match.group(1) if match else None
            if key and key in kwargs and key != "file":
                print("USD flag skipped (unsupported by this mayaUsd): " + key)
                del kwargs[key]
                continue
            raise


def _sanitize_prim_name(name):
    """Mirror of the USD prim-name rewrite (probe-verified: mayaUSDExport turns
    ``ref:nsCube`` into ``ref_nsCube``): every char outside ``[A-Za-z0-9_]``
    becomes ``_``, and a leading digit is PREFIXED with ``_``. The sidecar must
    record what the exporter actually writes. Keep identical to the mayatk twin.
    """
    if not name:
        return "_"
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if name[0].isdigit():
        name = "_" + name
    return name


def _resolved_file(cmds, file_node):
    """Absolute path of a file node's texture, workspace-resolved; None if absent."""
    try:
        path = cmds.getAttr(f"{file_node}.fileTextureName")
    except Exception:
        return None
    if not path:
        return None
    if not os.path.isfile(path):
        try:
            expanded = cmds.workspace(expandName=path)
            if os.path.isfile(expanded):
                path = expanded
        except Exception:
            pass
    return os.path.abspath(path) if os.path.isfile(path) else None


def _material_slots(cmds, mat, node_type):
    """``{logical channel: file}`` for *mat*, or ``{}`` when the slots are unknowable.

    Only the Stingray family declares its inputs; the surface family is walked
    through history, where a file node carries no reliable channel. Returned
    alongside (never instead of) the flat file list -- see
    ``STINGRAY_SLOT_CHANNELS``.
    """
    slots = {}
    if node_type not in STINGRAY_SHADER_TYPES:
        return slots
    for slot, channel in STINGRAY_SLOT_CHANNELS.items():
        src = _plug_source(cmds, f"{mat}.{slot}")
        if not src:
            continue
        path = _resolved_file(cmds, src.split(".")[0])
        if path:
            slots[channel] = path
    return slots


def _material_files(cmds, mat, node_type):
    """The texture files feeding *mat* -- the payload FBX cannot carry.

    Stingray reads its declared TEX_* slots (history would drag in the env/BRDF
    plumbing); the surface family walks history (user-built networks are free-form).
    """
    files = []
    if node_type in STINGRAY_SHADER_TYPES:
        for slot in STINGRAY_TEX_SLOTS:
            src = _plug_source(cmds, f"{mat}.{slot}")
            if src:
                path = _resolved_file(cmds, src.split(".")[0])
                if path:
                    files.append(path)
    else:
        for node in cmds.listHistory(mat) or []:
            try:
                if cmds.nodeType(node) == "file":
                    path = _resolved_file(cmds, node)
                    if path:
                        files.append(path)
            except Exception:
                continue
    return sorted(set(files), key=files.index)


def _sg_member_prims(cmds, sg):
    """Prim-spelled transform names assigned to *sg* (what the USD-imported
    Blender objects are named: ``_sanitize_prim_name`` of the short name, the
    namespace folded in)."""
    names = []
    for member in cmds.sets(sg, query=True) or []:
        node = member.split(".")[0]
        try:
            if cmds.nodeType(node) != "transform":
                parents = cmds.listRelatives(node, parent=True) or []
                node = parents[0] if parents else node
        except Exception:
            pass
        name = _sanitize_prim_name(node.split("|")[-1])
        if name not in names:
            names.append(name)
    return names


def collect_materials(cmds):
    """The texture manifest the FBX route ships, for the USD route -- read off
    the ORIGINAL shaders before ``usd_safe_materials`` rewires anything.

    The native USD materials are the baseline; the manifest is what guarantees
    parity with the FBX route regardless of what mayaUsd's shading exporter can
    express (it writes no normal map off a bump2d chain, no packed metallic /
    roughness / AO maps, no AO at all -- probed). The Blender side rebuilds each
    textured material from these files exactly as it does off an FBX.

    Returns ``(entries, shading_groups)``: one entry per textured material
    (``name`` = the shader's short name the Blender material ends up with,
    ``fbx_material`` = the same, since the shading-group-named USD material is
    renamed to it Blender-side before the replay, ``objects`` prim-spelled), and
    ``{prim-spelled shading group: shader short name}`` for that rename -- every
    material, textured or not, so a flat material stops wearing its SG's name.
    """
    entries, shading_groups, seen = [], {}, {}
    for sg in cmds.ls(type="shadingEngine") or []:
        try:
            src = _plug_source(cmds, f"{sg}.surfaceShader")
            if not src:
                continue
            mat = src.split(".")[0]
            short = mat.split("|")[-1].split(":")[-1]
            shading_groups[_sanitize_prim_name(sg.split("|")[-1])] = short
            if mat in seen:
                for member in _sg_member_prims(cmds, sg):
                    if member not in seen[mat]["objects"]:
                        seen[mat]["objects"].append(member)
                continue
            node_type = cmds.nodeType(mat)
            files = _material_files(cmds, mat, node_type)
            if not files:
                continue  # nothing to rebuild; the native USD material stands
            members = _sg_member_prims(cmds, sg)
            if not members:
                # Assigned to nothing: no prim binds it, so the layer carries
                # no material to rebuild onto (the FBX route warns per entry).
                print("texture manifest: {} unassigned, not carried".format(short))
                continue
            entry = {
                "name": short,
                "shader_type": node_type,
                "fbx_material": short,
                "objects": members,
                "files": files,
                "slots": _material_slots(cmds, mat, node_type),
            }
            entries.append(entry)
            seen[mat] = entry
        except Exception:
            print(f"material manifest skipped for {sg}:")
            traceback.print_exc()
    print("texture manifest: {} textured material(s)".format(len(entries)))
    return entries, shading_groups


def _export_ready_skins(cmds, frames, root_parent):
    """One shear-free skeleton per mesh skin, before the export reads the scene.

    mayaUsd's exporter writes NO skin for a skinCluster whose influences do not share
    one root joint -- silently: the deformed points get baked per frame instead
    and Blender streams them from the payload (measured: 14 production wire
    looms, each skinned to a joint chain plus an anchor joint under a second
    root). Blender's FBX importer fails the same skin differently (two armatures,
    the mesh parented to the wrong one), so both routes run this. mayatk's
    ``SkinUtils.flatten_influences`` reparents every influence flat under one
    new root with world-fitted keys at *frames* -- the joint locals are then
    TRS-exact too, where a stretched chain shears -- and un-pins the skinned
    meshes for an armature-relative importer. *root_parent* is where that root
    goes, and the two importers need different answers: ``"ancestor"`` (USD)
    keeps the skeleton on the mesh's own parent chain, ``"world"`` (FBX) puts
    it in a new top-level group, because Blender's FBX importer places a
    skinned mesh from its armature node's LOCAL bind matrix -- right only for a
    top-level armature node (nested: seven production looms 2.4-3.7 m out).
    Guarded like the FBX route's smart bake: without mayatk on ``PYTHONPATH``
    the export proceeds as authored and says so.

    Returns the manifest's ``bones`` section -- ``{joint: the joint that was its
    parent}``, short names, only where both ends are flattened influences. The
    flatten is what removes that hierarchy and nothing in the payload records it,
    yet both importers size a bone from the distance to its children: a skeleton
    of siblings arrives drawn at the ROOT's spread (measured: 2.49 m bones on a
    loom whose joints sit 0.89 cm apart). Blender re-derives the lengths from
    this; the joint transforms stay flat, which is what keeps them exact.
    """
    try:
        from mayatk.rig_utils.skinning import SkinUtils
    except Exception as error:
        print(
            "skins: mayatk unavailable ({}); a skin spanning several joint roots "
            "exports as baked points.".format(error)
        )
        return {}
    try:
        roots = SkinUtils.flatten_influences(
            frames=frames, root_parent=root_parent, orient_bones=True
        )
    except Exception:
        print("skins: flatten failed; skins export as authored.")
        traceback.print_exc()
        return {}
    bones = {}
    for root, influences in roots.items():
        # Short names: the parents were read BEFORE the flatten, so their long
        # paths are stale -- and a bone is named for the joint either way.
        shorts = set(path.rsplit("|", 1)[-1] for path in influences)
        for path, parent in influences.items():
            parent = parent.rsplit("|", 1)[-1]
            if parent in shorts:
                bones[path.rsplit("|", 1)[-1]] = parent
        print(
            "skins: {} <- {} influence(s)".format(
                root.rsplit("|", 1)[-1], len(influences)
            )
        )
    return bones


def collect_instance_groups(cmds):
    """Maya instance sets -> ``[[sanitized prim paths sharing one shape], ...]``.

    The export FLATTENS instances (see ``exportInstances`` above), which is what
    keeps materials intact -- but flattening alone would hand Blender N
    independent meshes and break the scene's memory profile. USD cannot carry
    the relationship for us: its instancing model produces read-only prototypes
    that Blender materializes as collection-instance Empties, not the linked
    duplicates a Blender artist edits (measured: both import modes fail, one
    with `prototypes` clutter, the other with zero data sharing).

    So the RELATIONSHIP travels as data, in the same sidecar the FBX route
    already uses, and ``_apply_instance_manifest`` rebuilds Blender-native
    shared mesh datablocks from it. Recorded, never inferred: hashing geometry
    would also fuse coincidentally-identical meshes, so editing one would
    silently change another.

    Recorded as FULL PRIM PATHS with every segment sanitized -- what
    ``mergeTransformAndShape=True`` writes (probe-verified: ``|g1|wheel`` ->
    ``/g1/wheel``, namespaced ``ref:nsCube`` -> ``/ref_nsCube``). Paths, not
    leaf names: prim paths are unique, so duplicate leaves stay matchable
    through Blender's ``.001`` collision renames. Two transforms whose paths
    sanitize identically (``ns:cube`` beside ``ns_cube``) are renamed apart
    unpredictably by the exporter, so a collision touching a recorded member
    fails the export loudly rather than shipping a sidecar that cannot match.
    """

    def prim_path(dag_path):
        return "/" + "/".join(
            _sanitize_prim_name(seg) for seg in dag_path.split("|") if seg
        )

    all_paths = {}
    for transform in cmds.ls(type="transform", long=True) or []:
        all_paths.setdefault(prim_path(transform), []).append(transform)

    groups = []
    for shape in cmds.ls(type="mesh", noIntermediate=True) or []:
        try:
            parents = cmds.listRelatives(shape, allParents=True, fullPath=True) or []
        except Exception:
            continue
        if len(parents) > 1:  # >1 parent transform == a Maya instance set
            groups.append([prim_path(p) for p in parents])

    colliding = {}
    for group in groups:
        for path in group:
            if len(all_paths.get(path, [])) > 1:
                colliding[path] = all_paths[path]
    if colliding:
        raise RuntimeError(
            "Transform paths collide after USD prim sanitization -- the "
            "exporter renames them apart unpredictably, so the instance sets "
            "could not be matched on the Blender side. Rename to distinct "
            "prim-safe names or pull via FBX: "
            + "; ".join("{} <- {}".format(k, v) for k, v in sorted(colliding.items()))
        )
    return groups


def scene_settings(cmds):
    """The scene's time setup -- the manifest's ``scene`` section, the one part of a
    scene neither intermediate round-trips whole (FBX carries the fps, USD the
    sampled range). Keys mirror ``btk.scene_settings`` / ``mtk.scene_settings``:
    ``fps`` (frames per second, from the API so a custom rate needs no name
    table), the playback range the timeline plays (``frame_start``/``frame_end``
    = Maya's min/max), the full animation range (``anim_start``/``anim_end`` =
    ast/aet) and ``frame_current``. Dependency-free copy of
    ``mtk.EnvUtils.scene_settings`` (the send direction's in-process reader),
    drift-guarded by
    ``mayatk/test/test_blender_bridge.py::TestPullTemplateCopiesMatchTheirSource``.
    """
    import maya.api.OpenMaya as om

    def playback(**flag):
        return cmds.playbackOptions(query=True, **flag)

    return {
        "fps": om.MTime(1.0, om.MTime.kSeconds).asUnits(om.MTime.uiUnit()),
        "frame_start": playback(minTime=True),
        "frame_end": playback(maxTime=True),
        "anim_start": playback(animationStartTime=True),
        "anim_end": playback(animationEndTime=True),
        "frame_current": cmds.currentTime(query=True),
    }


def _transfer_rig(cmds, frames):
    """Rig mode (schema 15.2): extract the RigGraph, plan it against the
    CONSUMER's capability (``RIG_CAPABILITY``, sent into this template), smart-
    bake ONLY what the plan says, and sample the built records' targets so the
    consumer can verify what it builds. Returns the manifest's ``rig`` section,
    or ``{}`` when mayatk is unavailable -- printed, never silent. Kept
    dependency-free and IDENTICAL between the FBX and USD templates (guarded)."""
    import json

    if not RIG_CAPABILITY:
        print("rig: no consumer capability was sent; nothing to plan against.")
        return {}
    try:
        from mayatk.rig_utils.rig_graph_extract import RigGraphExtractor
        from pythontk import RigCapability, RigGraph, RigPlanner
    except Exception as error:
        print("rig: mayatk unavailable ({}); rig logic is not carried.".format(error))
        return {}
    try:
        data = RigGraphExtractor().extract()
        graph = RigGraph.from_dict(data)
        plan = RigPlanner.plan(
            graph, RigCapability.from_dict(json.loads(RIG_CAPABILITY))
        )
    except Exception:
        print("rig: extraction or planning failed; rig logic is not carried.")
        traceback.print_exc()
        return {}
    coverage = graph.coverage()
    print(
        "rig: {} record(s); {} to build, {} node(s) to bake, {} unaccounted driver(s).".format(
            len(data["records"]),
            len(plan.build),
            len(plan.bake),
            coverage["unaccounted"],
        )
    )
    path_of = {n["id"]: n.get("path") for n in data["nodes"]}
    bake_paths = [
        path_of[i] for i in plan.bake if path_of.get(i) and cmds.objExists(path_of[i])
    ]
    if bake_paths and INCLUDE_ANIMATION:
        try:
            from mayatk.anim_utils.smart_bake._smart_bake import SmartBake

            result = SmartBake(
                objects=bake_paths,
                use_override_layer=True,
                bake_blend_shapes=True,
                bake_inherited_visibility=False,
                optimize_keys=False,
                restorable=False,
            ).execute()
            print(
                "rig: baked {} object(s) the plan could not build.".format(
                    result.baked_count
                )
            )
        except Exception:
            print("rig: scoped bake failed; unbuilt records arrive static.")
            traceback.print_exc()
    verify_frames = sorted(
        {
            f
            for rid in plan.build
            for f in (plan.verify.get(rid, {}).get("frames") or [])
        }
    )
    if not verify_frames:
        verify_frames = (
            [frames[0], frames[-1]] if frames else [cmds.currentTime(query=True)]
        )
    targets = sorted({i for rid in plan.build for i in graph.record(rid).target_ids()})
    samples = {}
    now = cmds.currentTime(query=True)
    try:
        for frame in verify_frames:
            cmds.currentTime(frame)
            for node_id in targets:
                path = path_of.get(node_id)
                if path and cmds.objExists(path):
                    samples.setdefault(node_id, {})[str(frame)] = cmds.xform(
                        path, query=True, worldSpace=True, translation=True
                    )
    finally:
        cmds.currentTime(now)
    return {
        "graph": data,
        "plan": plan.to_dict(),
        "coverage": coverage,
        "verify_samples": samples,
    }


def _classify_rig_machinery(cmds, rig=None):
    """Answer what each Maya node IS; ``ptk.RigMachinery`` names the apparatus.

    A carrier ships every DAG node as an object, so a rig that could not travel
    arrives TWICE over: its motion, as keys on whatever renders, AND the whole
    apparatus that used to produce that motion -- constraint nodes, IK handles
    and effectors, control curves, up-vector locators, the groups that hold only
    those, and joints nothing content is skinned to. In the target that apparatus
    selects, draws and drives nothing. On the production module it is 924 of 2727
    transforms, landing as ~1100 inert objects around 1505 meshes, which is
    exactly what "the rig is poorly reconstructed" looks like from the outside --
    and it lands identically in BAKE mode, because baking never removed it.

    Named here rather than DELETED here, deliberately. The FBX route bakes before
    it writes, but the USD route has no bake at all (mayaUsd samples the live
    scene per frame), so deleting a constraint on this side would delete the
    motion it was about to sample. What this names, the consumer drops once the
    payload is in: that costs one carrier's worth of nodes and can never cost a
    frame of animation.

    Only the FACTS are Maya's, and they are all this decides: what each node is
    (one of ``RigMachinery.KINDS``, else ``CONTENT`` -- the shape test is a
    DENYLIST, so an unknown shape type counts as content and survives), which
    nodes are load-bearing (every influence of a skinCluster that deforms
    content -- one deforming only the rig's own IK curve protects nothing -- and,
    under ``rig`` mode, every node a BUILT record names, since the consumer
    resolves those ids in the delivered scene), and which nodes ARE the rig (the
    graph's own nodes, plus every constraint and IK node). The rule that turns
    those into an answer -- protection propagating up, the sweep down, ambiguity
    resolved in favour of keeping -- is one shared implementation, so both
    directions of a hand-off can hold the same opinion.

    Parameters:
        cmds: ``maya.cmds``.
        rig: The manifest's ``rig`` section when rig mode built one (schema
            15.3); its graph is reused. Without it the graph is extracted here
            (0.3 s of the census's 1.9 s on the production module), so bake mode
            names the same set.

    Returns:
        dict: ``{maya dag path: kind}``. Empty when nothing qualifies, and empty
        on ANY failure: this is a cleanup, never a reason to lose a conversion.
    """
    machinery_shapes = ("nurbsCurve", "bezierCurve", "locator")
    try:
        from pythontk import RigMachinery
    except Exception as error:
        print(
            "rig: pythontk unavailable ({}); the rig's apparatus travels with "
            "it.".format(error)
        )
        return {}
    try:
        transforms = cmds.ls(type="transform", long=True) or []
        if not transforms:
            return {}
        nodes = {}
        for node in transforms:
            node_type = cmds.nodeType(node)
            shapes = [
                cmds.nodeType(s)
                for s in (
                    cmds.listRelatives(
                        node, shapes=True, fullPath=True, noIntermediate=True
                    )
                    or []
                )
            ]
            if any(s not in machinery_shapes for s in shapes):
                kind = RigMachinery.CONTENT
            elif node_type.endswith("Constraint"):
                kind = "constraint"
            elif node_type in ("ikHandle", "ikEffector"):
                kind = "ik"
            elif node_type == "joint":
                kind = "joint"  # nothing content is skinned to it
            elif shapes:
                kind = "locator" if set(shapes) == {"locator"} else "control"
            else:
                kind = "group"
            nodes[node] = kind

        protected = []
        for skin in cmds.ls(type="skinCluster") or []:
            geometry = cmds.skinCluster(skin, query=True, geometry=True) or []
            if not any(cmds.nodeType(g) not in machinery_shapes for g in geometry):
                continue  # deforms only the rig's own curve: its joints are rig too
            for influence in cmds.skinCluster(skin, query=True, influence=True) or []:
                protected.extend(cmds.ls(influence, long=True) or [])

        graph = (rig or {}).get("graph")
        if graph is None:
            try:
                from mayatk.rig_utils.rig_graph_extract import RigGraphExtractor

                graph = RigGraphExtractor().extract()
            except Exception as error:
                print(
                    "rig: no graph to name the apparatus from ({}); only "
                    "constraint and IK nodes are named.".format(error)
                )
                graph = {}
        path_of = {n.get("id"): n.get("path") for n in graph.get("nodes") or []}
        build = set(((rig or {}).get("plan") or {}).get("build") or [])
        for record in graph.get("records") or []:
            if record.get("id") not in build:
                continue
            ids = [(record.get("target") or {}).get("id")]
            ids += [s.get("id") for s in record.get("sources") or []]
            for node_id in ids:
                path = path_of.get(node_id)
                protected.extend((cmds.ls(path, long=True) or []) if path else ())

        seeds = set()
        for path in path_of.values():
            seeds.update((cmds.ls(path, long=True) or []) if path else ())
        for node_type in ("constraint", "ikHandle", "ikEffector"):
            seeds.update(cmds.ls(type=node_type, long=True) or [])

        kinds = RigMachinery.classify(nodes, seeds=seeds, protected=protected)
        # Every DAG node, not just transforms: a USD payload lands each SHAPE as
        # its own object too, so a shape's name is in the consumer's namespace.
        kinds, dropped = RigMachinery.unambiguous(
            kinds, cmds.ls(dag=True, long=True) or []
        )
        if dropped:
            print(
                "rig: {} apparatus node(s) share a short name with a node that "
                "must survive; kept.".format(len(dropped))
            )
        return kinds
    except Exception:
        print("rig: machinery census failed; the rig's apparatus travels with it.")
        traceback.print_exc()
        return {}


def write_manifest(
    cmds,
    materials=None,
    shading_groups=None,
    bones=None,
    shots=None,
    rig=None,
    machinery=None,
):
    """Sidecar beside the USD carrying what USD itself cannot: instance groups,
    the scene's time setup (``scene`` -- the stage carries the fps and only
    the SAMPLED range, which is narrowed to what moves; see
    ``_animation_frame_range``), and the joint hierarchy the skin pre-pass
    flattened away (``bones`` -- see ``_export_ready_skins``), and the rig
    apparatus the bake left inert (``machinery`` -- see
    ``_classify_rig_machinery``).

    ALWAYS written for the USD route (empty groups included), so the Blender
    side can tell "no instances" from "sidecar lost" -- it REQUIRES the file.
    Raises on failure; main() then withholds the USD artifact, so the parent's
    judged-by-artifact contract reports a failed conversion instead of shipping
    a payload that would import silently flattened.
    """
    import json

    groups = collect_instance_groups(cmds)
    data = {
        "version": 2,
        "format": "paths",
        "instances": groups,
        "materials": materials or [],
        "shading_groups": shading_groups or {},
        "scene": scene_settings(cmds),
        "bones": bones or {},
        **({"rig": rig} if rig else {}),
        **({"machinery": machinery} if machinery else {}),
    }
    if shots:  # absent = nothing to say; the consumer gates on presence
        data["shots"] = shots
    with open(OUT_USD + ".manifest.json", "w", encoding="utf-8") as fh:
        json.dump(data, fh)
    print(
        "instance manifest: {} group(s) covering {} transforms".format(
            len(groups), sum(len(g) for g in groups)
        )
    )
    if machinery:
        print(
            "rig: {} baked-rig node(s) named for the consumer to drop.".format(
                len(machinery)
            )
        )


def _progress(done, total, text):
    """A ``pythontk.ProgressRelay`` marker line, flushed so the parent's footer sees it
    while the conversion runs. Spelled out: the marker protocol needs no import."""
    print("::progress:: {}/{} {}".format(done, total, text), flush=True)


def main():
    import maya.standalone

    _progress(0, 5, "Starting Maya")
    maya.standalone.initialize(name="python")
    import maya.cmds as cmds

    workspace = _resolve_workspace(cmds, SRC_PATH)
    print("workspace: " + (workspace or "none found (Maya fallback resolution only)"))
    _progress(0, 5, "Opening the scene")
    _open_scene(cmds, SRC_PATH)
    # Read off the ORIGINAL scene, before the skin pass rewrites its curves: the
    # section describes what the artist authored. Names spelled as the exporter
    # writes the prims.
    shots = shots_section(cmds, lambda name: _sanitize_prim_name(name.split("|")[-1]))
    # Read off the ORIGINAL networks: the usd-safe pass rewires them.
    _progress(1, 5, "Translating materials")
    materials, shading_groups = collect_materials(cmds)
    usd_safe_materials(cmds)
    # Sample only the frames that carry motion -- see _animation_frame_range for
    # the measured cost of getting this wrong. Decided BEFORE the skin pass keys
    # every influence at each of them.
    frame_range = _animation_frame_range(cmds) if INCLUDE_ANIMATION else None
    _progress(2, 5, "Preparing skins")
    bones = _export_ready_skins(
        cmds,
        range(int(frame_range[0]), int(frame_range[1]) + 1)
        if frame_range
        else [cmds.currentTime(query=True)],
        "ancestor",
    )
    rig = {}
    if RIG_MODE == "rig":
        _progress(2, 5, "Transferring the rig")
        rig = _transfer_rig(
            cmds,
            list(range(int(frame_range[0]), int(frame_range[1]) + 1))
            if frame_range
            else [cmds.currentTime(query=True)],
        )
    # Named now, dropped by the consumer once the payload is in: deleting it
    # HERE would delete the motion mayaUsd is about to sample (this route has no
    # bake of its own). `raw` asks for the scene untouched, apparatus included.
    machinery = {} if RIG_MODE == "raw" else _classify_rig_machinery(cmds, rig)
    if not cmds.pluginInfo("mayaUsdPlugin", query=True, loaded=True):
        cmds.loadPlugin("mayaUsdPlugin")
    _progress(3, 5, "Writing the USD")
    export_usd(cmds, frame_range)
    _progress(4, 5, "Writing the manifest")
    # AFTER the export: the sidecar describes the scene the USD was written
    # from. A failure in either withholds both (`_withhold`): a USD without its
    # sidecar would import silently flattened.
    write_manifest(
        cmds,
        materials,
        shading_groups,
        bones,
        shots=shots,
        rig=rig,
        machinery=machinery,
    )
    _progress(5, 5, "Converted")


def shots_section(cmds, spell):
    """The scene's shots as the manifest's ``shots`` section, or ``None``.

    Neither carrier has a place for a shot, a marker, a locked gap or the samples
    the sequencer planted on shot bounds, so the store crosses as data and
    ``MayaSceneImport`` rebuilds it 1:1. mayatk's store encodes it
    (``ShotStore.export_transfer`` over ``pythontk.ShotTransfer``), names spelled
    by *spell* as the carrier will write them. Guarded like the other mayatk
    pre-passes: without mayatk on ``PYTHONPATH`` the shots are not carried, and a
    printed line says so.
    """
    try:
        from mayatk.anim_utils.shots._shots import ShotStore
    except Exception as error:  # noqa: BLE001 -- degrade, never fail the conversion
        print("shots: mayatk unavailable ({}); not carried.".format(error))
        return None
    try:
        return ShotStore.export_transfer(spell=spell)
    except Exception:  # noqa: BLE001
        print("shots: could not read the scene's shots; not carried:")
        traceback.print_exc()
        return None


def _exit(code):
    """Leave without teardown. ``os._exit`` is not enough on Windows: it still runs
    every DLL's detach, where Maya's static destructors fault and its crash handler
    saves the open scene into the temp dir -- a 366 MB ``[Recovered]`` copy per
    production conversion (measured). ``pythontk.ProcessExit`` skips detach; without
    pythontk on the path this degrades to ``os._exit``."""
    sys.stdout.flush()
    sys.stderr.flush()
    try:
        from pythontk.core_utils.process_exit import ProcessExit
    except Exception:  # noqa: BLE001 -- the exit must never raise
        os._exit(code)
    ProcessExit.hard_exit(code)


def _withhold(artifact):
    """Remove *artifact* and its sidecar after a failed run: whatever it left
    behind must never pass as the conversion.

    Success is judged by the artifact, and an exporter can fail AFTER opening its
    file -- Maya's USD exporter writes a layer before it refuses a scene
    (measured: a root-level joint), so the partial payload passed, the non-zero exit was
    tolerated as a teardown crash, and the caller reported a missing sidecar in
    place of the exporter's own message. A payload whose sidecar failed is as
    wrong: it imports without what the sidecar rebuilds."""
    for path in (artifact, artifact + ".manifest.json"):
        try:
            os.remove(path)
        except OSError:
            pass


try:
    main()
except Exception:
    traceback.print_exc()
    _withhold(OUT_USD)
    _exit(1)
# Success is judged by the artifact; skip standalone teardown (known access violations).
_exit(0)
