# Maya-scene -> FBX conversion script (Maya -> Blender pull). Generated by MayaSceneImport -- do not edit by hand.

"""Open a Maya scene headlessly (mayapy) and export it as FBX for a Blender import.

The Maya half of ``btk.import_maya_scene``: runs under ``mayapy`` via
``pythontk.run_script_to_artifact``, which judges success by the exported FBX's
existence -- NOT the exit code (standalone teardown is a known crasher, hence the
``os._exit`` below, which skips it entirely).

The scene is opened for conversion only and never saved, so it may be mutated
freely to maximize FBX fidelity: modern surface shaders (standardSurface /
aiStandardSurface / openPBRSurface -- the Maya 2020+ defaults) are translated to
phong before export, because FBX carries only the classic Lambert/Phong material
model and silently drops their textures otherwise (verified empirically: a
standardSurface baseColor file texture arrives in Blender only after translation).

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).

Skin pre-pass (optional, both routes): a skinCluster whose influences span more
than one root joint defeats both importers -- see ``_export_ready_skins``, which
hands mayatk's ``SkinUtils.flatten_influences`` the frames this export bakes.

Smart-bake pre-pass (optional): FBX's ``BakeComplexAnimation`` carries plain
keyframes but silently drops *inherited* visibility (a child whose show/hide comes
from an animated ancestor) and can miss set-driven keys / motion paths. When
``SMART_BAKE`` is requested AND a cheap dependency-free probe finds driven
animation, this bakes those channels to real keys first via mayatk's ``SmartBake``
-- the ONE existing engine for it (reused, not reimplemented). Baked visibility
additionally travels in the manifest sidecar's ``visibility`` section (beside the
``materials`` the manifest already carries): the FBX *does* carry the visibility
curve, but Blender's FBX importer drops it (verified empirically -- even
directly-keyed visibility arrives as nothing), so the Blender side replays the
manifest as ``hide_render``/``hide_viewport`` keys. The
core conversion stays dependency-free: the mayatk import is guarded and injected
on ``PYTHONPATH`` by the driver only when smart-bake is active, so a pipeline
mayapy without mayatk degrades to the plain FBX bake.
"""

# Dependency-free Maya Python by default: the core conversion imports only Maya's
# own modules. The OPTIONAL smart-bake pre-pass imports mayatk, but behind a guard
# (missing -> plain FBX bake), so this template still runs on a bare mayapy.
import json
import os
import sys
import traceback

SRC_PATH = r"__SRC_PATH__"
OUT_FBX = r"__OUT_FBX__"
EMBED_TEXTURES = __EMBED_TEXTURES__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__
# "auto" = bake only if the cheap probe finds driven animation; True = always try;
# False = never (the pre-smart-bake behaviour).
SMART_BAKE = __SMART_BAKE__
# "rig" carries the rig logic as a RigGraph planned against the CONSUMER's
# capability (sent in as RIG_CAPABILITY, a JSON string); the whole-scene smart
# bake is then off and only what the plan cannot build is baked. Schema 15.
RIG_MODE = __RIG_MODE__
RIG_CAPABILITY = __RIG_CAPABILITY__

# Concrete constraint node types (``ls`` has no reliable abstract "constraint"
# filter across versions) — the cheap probe's first signal of driven animation.
_CONSTRAINT_TYPES = (
    "parentConstraint",
    "pointConstraint",
    "orientConstraint",
    "scaleConstraint",
    "aimConstraint",
    "poleVectorConstraint",
    "geometryConstraint",
    "normalConstraint",
    "tangentConstraint",
)

# Modern surface shaders whose textures FBX cannot carry (classic model only).
MODERN_SHADER_TYPES = ("standardSurface", "aiStandardSurface", "openPBRSurface")
# ShaderFX game shaders: FBX writes them as a "Maya|TEX_*" custom-property set
# that Blender's importer ignores outright ("material link ... ignored").
STINGRAY_SHADER_TYPES = ("StingrayPBS", "ShaderfxShader")
# The StingrayPBS texture slots worth carrying (the env/IBL cubes and BRDF lut
# are renderer plumbing, not material textures).
STINGRAY_TEX_SLOTS = (
    "TEX_color_map",
    "TEX_normal_map",
    "TEX_metallic_map",
    "TEX_roughness_map",
    "TEX_ao_map",
    "TEX_emissive_map",
)
# Stingray slot -> the logical channel vocabulary the manifest speaks (the same
# names mtk's MatManifest emits, resolved Blender-side through
# ptk.MapRegistry.resolve_type_from_channel). Lets the applier rebuild a texture
# whose FILENAME carries no map-type token -- a plain color map named after a
# product would otherwise be unclassifiable. Spelled out rather than imported:
# this template is dependency-free by contract.
STINGRAY_SLOT_CHANNELS = {
    "TEX_color_map": "baseColor",
    "TEX_normal_map": "normal",
    "TEX_metallic_map": "metallic",
    "TEX_roughness_map": "roughness",
    "TEX_ao_map": "ambientOcclusion",
    "TEX_emissive_map": "emission",
}


def _ns_safe(name):
    """*name* with namespace colons flattened (``ns:mat`` -> ``ns_mat``).

    Nodes we CREATE must live at the root namespace under a colon-free name:
    a referenced scene's materials are namespaced (``loadReferenceDepth="all"``),
    and a colon in the exported node name is at the mercy of the FBX exporter's
    mangling -- the Blender-side slot match then silently misses. A flat name
    round-trips verbatim."""
    return name.replace(":", "_")


def _plug_source(cmds, attr):
    """Return the source plug connected into *attr*, or None."""
    try:
        cons = cmds.listConnections(attr, source=True, destination=False, plugs=True)
        return cons[0] if cons else None
    except Exception:
        return None


def _get_first(cmds, node, names, default):
    """First readable attribute value among *names* (attr-name drift across the
    standardSurface family), else *default*."""
    for name in names:
        try:
            value = cmds.getAttr(f"{node}.{name}")
            return value[0] if isinstance(value, list) else value
        except Exception:
            continue
    return default


def _roughness_to_cosine_power(rough):
    return max(2.0, min(100.0, 2.0 / max(rough * rough, 1e-4) - 2.0))


def _translate_surface(cmds, mat, phong):
    """standardSurface family -> phong: re-point maps, approximate scalars."""
    # base color (+map): the channel the user actually noticed missing
    color_src = _plug_source(cmds, f"{mat}.baseColor")
    if color_src:
        cmds.connectAttr(color_src, f"{phong}.color", force=True)
    else:
        c = _get_first(cmds, mat, ("baseColor",), (0.5, 0.5, 0.5))
        w = _get_first(cmds, mat, ("base", "baseWeight"), 1.0)
        cmds.setAttr(f"{phong}.color", c[0] * w, c[1] * w, c[2] * w, type="double3")

    # emission -> incandescence (+map). Gated on the weight: standardSurface's
    # emission weight DEFAULTS to 0, so a stray emissionColor map that emits
    # nothing in Maya must not glow in Blender. Weight clamped to 1 --
    # openPBR's emissionLuminance is in nits and would blow out the color.
    emit_w = min(
        _get_first(cmds, mat, ("emission", "emissionWeight", "emissionLuminance"), 0.0),
        1.0,
    )
    if emit_w > 0.0:
        emit_src = _plug_source(cmds, f"{mat}.emissionColor")
        if emit_src:
            cmds.connectAttr(emit_src, f"{phong}.incandescence", force=True)
        else:
            e = _get_first(cmds, mat, ("emissionColor",), (0.0, 0.0, 0.0))
            cmds.setAttr(
                f"{phong}.incandescence",
                e[0] * emit_w,
                e[1] * emit_w,
                e[2] * emit_w,
                type="double3",
            )

    # normal / bump chain rides as-is
    normal_src = _plug_source(cmds, f"{mat}.normalCamera")
    if normal_src:
        cmds.connectAttr(normal_src, f"{phong}.normalCamera", force=True)

    # specular: color * weight; roughness approximated as cosinePower
    sc = _get_first(cmds, mat, ("specularColor",), (1.0, 1.0, 1.0))
    sw = _get_first(cmds, mat, ("specular", "specularWeight"), 0.0)
    cmds.setAttr(
        f"{phong}.specularColor", sc[0] * sw, sc[1] * sw, sc[2] * sw, type="double3"
    )
    rough = _get_first(cmds, mat, ("specularRoughness", "roughness"), 0.4)
    cmds.setAttr(f"{phong}.cosinePower", _roughness_to_cosine_power(rough))

    # opacity -> transparency (inverse)
    o = _get_first(cmds, mat, ("opacity",), (1.0, 1.0, 1.0))
    if min(o) < 1.0:
        cmds.setAttr(
            f"{phong}.transparency", 1.0 - o[0], 1.0 - o[1], 1.0 - o[2], type="double3"
        )


def _translate_stingray(cmds, mat, phong):
    """StingrayPBS (ShaderFX) -> phong: carry color / normal / emissive maps.

    Metallic-workflow maps (metallic / roughness / ao) have no slot in FBX's
    classic material model -- they are dropped, and the conversion log says so.
    ``use_*_map`` toggles are honored (a wired-but-disabled map stays off).
    """

    def use(flag):
        return bool(_get_first(cmds, mat, (flag,), 0))

    color_src = _plug_source(cmds, f"{mat}.TEX_color_map")
    if color_src and use("use_color_map"):
        cmds.connectAttr(color_src, f"{phong}.color", force=True)
    else:
        c = _get_first(cmds, mat, ("base_color",), (0.5, 0.5, 0.5))
        cmds.setAttr(f"{phong}.color", c[0], c[1], c[2], type="double3")

    normal_src = _plug_source(cmds, f"{mat}.TEX_normal_map")
    if normal_src and use("use_normal_map"):
        # Classic-model normal maps ride via a tangent-space bump2d chain.
        file_node = normal_src.split(".")[0]
        bump = cmds.shadingNode(
            "bump2d", asUtility=True, name=f"{_ns_safe(mat)}_fbxsafe_bump"
        )
        cmds.setAttr(f"{bump}.bumpInterp", 1)  # tangent-space normals
        try:
            cmds.connectAttr(f"{file_node}.outAlpha", f"{bump}.bumpValue", force=True)
        except Exception:
            pass  # non-file source; the exporter still reads the chain's texture
        cmds.connectAttr(f"{bump}.outNormal", f"{phong}.normalCamera", force=True)

    # Gated on intensity like the standardSurface emission weight: a wired map
    # with intensity 0 emits nothing in Maya and must not glow in Blender.
    # (Unreadable intensity — a ShaderFX variant — defaults to letting the map ride.)
    emis_src = _plug_source(cmds, f"{mat}.TEX_emissive_map")
    if (
        emis_src
        and use("use_emissive_map")
        and _get_first(cmds, mat, ("emissive_intensity",), 1.0) > 0.0
    ):
        cmds.connectAttr(emis_src, f"{phong}.incandescence", force=True)

    rough = _get_first(cmds, mat, ("roughness",), 0.4)
    cmds.setAttr(f"{phong}.cosinePower", _roughness_to_cosine_power(rough))

    dropped = [
        name
        for name in ("metallic", "roughness", "ao")
        if _plug_source(cmds, f"{mat}.TEX_{name}_map")
    ]
    if dropped:
        print(
            f"{mat}: no classic-FBX slot for {', '.join(dropped)} map(s) -- not carried"
        )


def _resolve_workspace(cmds, scene_path):
    """Open the Maya project owning *scene_path* (nearest workspace.mel above it).

    Without it, headless Maya cannot resolve project-relative texture paths
    (``sourceimages/...``): the FBX then carries unresolvable strings (pink
    materials in Blender -- Blender's image search only looks near the FBX,
    which sits in the temp dir) and the manifest collects no files. Returns the
    project root, or None when the scene lives outside any project.
    """
    directory = os.path.dirname(os.path.abspath(scene_path))
    while True:
        if os.path.isfile(os.path.join(directory, "workspace.mel")):
            try:
                cmds.workspace(directory, openWorkspace=True)
                return directory
            except Exception:
                return None
        parent = os.path.dirname(directory)
        if parent == directory:
            return None
        directory = parent


def _open_scene(cmds, path):
    """Open *path*, tolerating the RuntimeError noise of a scene that LOADED but
    reported errors -- missing renderer plugins, unknown nodes, deprecated
    requires lines (routine for production scenes on a vanilla mayapy). The
    content is in memory either way; aborting the whole conversion over it
    costs the user an import that would have worked. A failed open -- nothing
    loaded -- still raises."""
    try:
        cmds.file(
            path, open=True, force=True, ignoreVersion=True, loadReferenceDepth="all"
        )
    except RuntimeError as error:
        opened = cmds.file(query=True, sceneName=True) or ""
        if os.path.normcase(os.path.abspath(opened)) != os.path.normcase(
            os.path.abspath(path)
        ):
            raise
        print("scene opened with load errors (tolerated): {}".format(error))


def _resolved_file(cmds, file_node):
    """Absolute path of a file node's texture, workspace-resolved; None if absent."""
    try:
        path = cmds.getAttr(f"{file_node}.fileTextureName")
    except Exception:
        return None
    if not path:
        return None
    if not os.path.isfile(path):
        try:
            expanded = cmds.workspace(expandName=path)
            if os.path.isfile(expanded):
                path = expanded
        except Exception:
            pass
    return os.path.abspath(path) if os.path.isfile(path) else None


def _material_slots(cmds, mat, node_type):
    """``{logical channel: file}`` for *mat*, or ``{}`` when the slots are unknowable.

    Only the Stingray family declares its inputs; the surface family is walked
    through history, where a file node carries no reliable channel. Returned
    alongside (never instead of) the flat file list -- see
    ``STINGRAY_SLOT_CHANNELS``.
    """
    slots = {}
    if node_type not in STINGRAY_SHADER_TYPES:
        return slots
    for slot, channel in STINGRAY_SLOT_CHANNELS.items():
        src = _plug_source(cmds, f"{mat}.{slot}")
        if not src:
            continue
        path = _resolved_file(cmds, src.split(".")[0])
        if path:
            slots[channel] = path
    return slots


def _material_files(cmds, mat, node_type):
    """The texture files feeding *mat* -- the payload FBX cannot carry.

    Stingray reads its declared TEX_* slots (history would drag in the env/BRDF
    plumbing); the surface family walks history (user-built networks are free-form).
    """
    files = []
    if node_type in STINGRAY_SHADER_TYPES:
        for slot in STINGRAY_TEX_SLOTS:
            src = _plug_source(cmds, f"{mat}.{slot}")
            if src:
                path = _resolved_file(cmds, src.split(".")[0])
                if path:
                    files.append(path)
    else:
        for node in cmds.listHistory(mat) or []:
            try:
                if cmds.nodeType(node) == "file":
                    path = _resolved_file(cmds, node)
                    if path:
                        files.append(path)
            except Exception:
                continue
    return sorted(set(files), key=files.index)


def _sg_member_names(cmds, sg):
    """Short transform names assigned to *sg* (namespace/path stripped -- what the
    FBX-imported Blender objects will be named after)."""
    names = []
    for member in cmds.sets(sg, query=True) or []:
        node = member.split(".")[0]
        try:
            if cmds.nodeType(node) != "transform":
                parents = cmds.listRelatives(node, parent=True) or []
                node = parents[0] if parents else node
        except Exception:
            pass
        short = node.split("|")[-1].split(":")[-1]
        if short not in names:
            names.append(short)
    return names


def fbx_safe_materials(cmds):
    """Swap every FBX-hostile shader for an equivalent phong on its shading group.

    Texture connections are re-pointed, scalar values approximated. Per-material
    failures degrade to the untranslated shader (gray in Blender) rather than
    aborting the conversion. The scene is throwaway -- nothing is restored, which
    is what lets each phong TAKE OVER its source material's name (the source is
    renamed aside) so the FBX carries the real names rather than an internal
    marker.

    ONE phong per source material: production scenes routinely feed one material
    into many shading groups (per-object SG splits, merged imports), and a
    per-SG translation explodes into "<mat>1..N" duplicates. Every SG of an
    already-translated material reuses its phong, and the manifest entry merges
    the member objects.

    Returns manifest entries for the translated materials: the original texture
    files (packed metallic/roughness/ao maps included -- FBX's classic model has
    no slot for them) so the Blender side can rebuild the material natively.
    """
    entries = []
    translated = {}  # source material -> (phong, entry)
    for sg in cmds.ls(type="shadingEngine") or []:
        try:
            src = _plug_source(cmds, f"{sg}.surfaceShader")
            if not src:
                continue
            mat = src.split(".")[0]
            if mat in translated:
                phong, entry = translated[mat]
                cmds.connectAttr(f"{phong}.outColor", f"{sg}.surfaceShader", force=True)
                for member in _sg_member_names(cmds, sg):
                    if member not in entry["objects"]:
                        entry["objects"].append(member)
                continue
            node_type = cmds.nodeType(mat)
            if node_type in MODERN_SHADER_TYPES:
                translate = _translate_surface
            elif node_type in STINGRAY_SHADER_TYPES:
                translate = _translate_stingray
            else:
                continue
            # The phong takes over the source material's NAME (the source is
            # moved aside first). That name is what rides in the FBX and becomes
            # the Blender material's name, so a translated material must not
            # arrive wearing an internal marker: "_fbxsafe" leaked into .blend
            # files and round-tripped back to Maya on the next send (live
            # production report). Only the manifest-driven rebuild used to undo
            # it -- an untextured or unclassifiable material kept the marker
            # forever. Renaming instead of decorating makes the FBX itself
            # truthful, so even a hand-rolled import gets the real name.
            leaf = _ns_safe(mat)
            try:
                source = cmds.rename(mat, "{}_src".format(leaf))
                phong_name = leaf
            except RuntimeError:  # locked/referenced -- keep the old marker
                source, phong_name = mat, "{}_fbxsafe".format(leaf)
            phong = cmds.shadingNode("phong", asShader=True, name=phong_name)
            translate(cmds, source, phong)
            cmds.connectAttr(f"{phong}.outColor", f"{sg}.surfaceShader", force=True)
            entry = {
                "name": mat.split(":")[-1],
                "shader_type": node_type,
                "fbx_material": phong,
                "objects": _sg_member_names(cmds, sg),
                "files": _material_files(cmds, source, node_type),
                "slots": _material_slots(cmds, source, node_type),
            }
            entries.append(entry)
            # Keyed by the node's CURRENT name: the other shading groups this
            # material feeds still point at it, and that is the name
            # ``_plug_source`` reports for them on the next iteration. Keying by
            # the pre-rename spelling would miss every one of them and re-translate
            # the material per shading group -- the duplicate explosion above.
            translated[source] = (phong, entry)
            print(
                "fbx-safe: {} -> {} ({} texture file(s) resolved)".format(
                    mat, phong, len(entry["files"])
                )
            )
        except Exception:
            print(f"fbx-safe translation skipped for {sg}:")
            traceback.print_exc()
    return entries


def _export_ready_skins(cmds, frames, root_parent):
    """One shear-free skeleton per mesh skin, before the export reads the scene.

    mayaUsd's exporter writes NO skin for a skinCluster whose influences do not share
    one root joint -- silently: the deformed points get baked per frame instead
    and Blender streams them from the payload (measured: 14 production wire
    looms, each skinned to a joint chain plus an anchor joint under a second
    root). Blender's FBX importer fails the same skin differently (two armatures,
    the mesh parented to the wrong one), so both routes run this. mayatk's
    ``SkinUtils.flatten_influences`` reparents every influence flat under one
    new root with world-fitted keys at *frames* -- the joint locals are then
    TRS-exact too, where a stretched chain shears -- and un-pins the skinned
    meshes for an armature-relative importer. *root_parent* is where that root
    goes, and the two importers need different answers: ``"ancestor"`` (USD)
    keeps the skeleton on the mesh's own parent chain, ``"world"`` (FBX) puts
    it in a new top-level group, because Blender's FBX importer places a
    skinned mesh from its armature node's LOCAL bind matrix -- right only for a
    top-level armature node (nested: seven production looms 2.4-3.7 m out).
    Guarded like the FBX route's smart bake: without mayatk on ``PYTHONPATH``
    the export proceeds as authored and says so.

    Returns the manifest's ``bones`` section -- ``{joint: the joint that was its
    parent}``, short names, only where both ends are flattened influences. The
    flatten is what removes that hierarchy and nothing in the payload records it,
    yet both importers size a bone from the distance to its children: a skeleton
    of siblings arrives drawn at the ROOT's spread (measured: 2.49 m bones on a
    loom whose joints sit 0.89 cm apart). Blender re-derives the lengths from
    this; the joint transforms stay flat, which is what keeps them exact.
    """
    try:
        from mayatk.rig_utils.skinning import SkinUtils
    except Exception as error:
        print(
            "skins: mayatk unavailable ({}); a skin spanning several joint roots "
            "exports as baked points.".format(error)
        )
        return {}
    try:
        roots = SkinUtils.flatten_influences(
            frames=frames, root_parent=root_parent, orient_bones=True
        )
    except Exception:
        print("skins: flatten failed; skins export as authored.")
        traceback.print_exc()
        return {}
    bones = {}
    for root, influences in roots.items():
        # Short names: the parents were read BEFORE the flatten, so their long
        # paths are stale -- and a bone is named for the joint either way.
        shorts = set(path.rsplit("|", 1)[-1] for path in influences)
        for path, parent in influences.items():
            parent = parent.rsplit("|", 1)[-1]
            if parent in shorts:
                bones[path.rsplit("|", 1)[-1]] = parent
        print(
            "skins: {} <- {} influence(s)".format(
                root.rsplit("|", 1)[-1], len(influences)
            )
        )
    return bones


# skinCluster.skinningMethod -> the UsdSkel token the Blender side maps onto an
# Armature modifier's Preserve Volume (Blender's own dual-quaternion skinning).
_SKINNING_METHODS = {0: "classicLinear", 1: "dualQuaternion", 2: "weightBlended"}


def skinning_methods(cmds):
    """``{mesh transform name: skinning method}`` for the manifest's ``skins``
    section. FBX carries a skin's method but Blender's importer never reads it,
    so every skin arrives linear; the USD route needs no record (mayaUsd authors
    ``primvars:skel:skinningMethod`` on the prim). Keyed by the transform's leaf
    name, the FBX sections' convention (meshes arrive under their Maya names)."""
    out = {}
    for sc in cmds.ls(type="skinCluster") or []:
        method = _SKINNING_METHODS.get(cmds.getAttr(sc + ".skinningMethod"))
        if not method:
            continue
        for shape in cmds.skinCluster(sc, query=True, geometry=True) or []:
            if cmds.nodeType(shape) != "mesh":
                continue
            for transform in (
                cmds.listRelatives(shape, parent=True, fullPath=True) or []
            ):
                out[transform.split("|")[-1]] = method
    return out


def scene_node_types(cmds):
    """``{leaf name: "locator" | "group"}`` -- the node-type sidecar section.

    Maya groups (shapeless transforms) and locators both travel as identical
    FBX nulls; Blender imports both as look-alike Empties. Recording which was
    which lets the Blender side stamp a ``maya_node_type`` custom property, so
    a later send BACK to Maya restores the correct node type instead of
    guessing from the children heuristic. A leaf name claimed by BOTH kinds is
    dropped -- a wrong tag is worse than the heuristic.

    Dependency-free copy of ``mtk.BlenderBridge._manifest_node_types`` (the send
    direction's in-process collector), drift-guarded by
    ``mayatk/test/test_blender_bridge.py::TestPullTemplateCopiesMatchTheirSource``.
    NOT "kept in step by hand", which is what this said while it was wrong twice over:

    * the leaf keeps its NAMESPACE. Maya's exporter writes ``ns:x`` literally and
      Blender keeps the colon, so a stripped key matches NOTHING on a referenced
      scene -- the production norm, and every locator on one came back a plain Empty.
    * only an EXACT ``transform`` counts. ``cmds.ls(type="transform")`` also returns
      joints (a derived type), so every shapeless joint in a rig was tagged a
      ``group``; one sharing a leaf name with a real group made that name ambiguous
      and dropped the group's correct tag.
    """
    out = {}
    ambiguous = set()
    for transform in cmds.ls(type="transform", long=True) or []:
        if cmds.nodeType(transform) != "transform":  # a joint is not a group
            continue
        shapes = cmds.listRelatives(transform, shapes=True, fullPath=True) or []
        if not shapes:
            node_type = "group"
        elif all(cmds.nodeType(s) == "locator" for s in shapes):
            node_type = "locator"
        else:
            continue
        leaf = transform.split("|")[-1]
        if out.get(leaf, node_type) != node_type:
            ambiguous.add(leaf)
        out[leaf] = node_type
    for leaf in ambiguous:
        out.pop(leaf, None)
    return out


def scene_settings(cmds):
    """The scene's time setup -- the manifest's ``scene`` section, the one part of a
    scene neither intermediate round-trips whole (FBX carries the fps, USD the
    sampled range). Keys mirror ``btk.scene_settings`` / ``mtk.scene_settings``:
    ``fps`` (frames per second, from the API so a custom rate needs no name
    table), the playback range the timeline plays (``frame_start``/``frame_end``
    = Maya's min/max), the full animation range (``anim_start``/``anim_end`` =
    ast/aet) and ``frame_current``. Dependency-free copy of
    ``mtk.EnvUtils.scene_settings`` (the send direction's in-process reader),
    drift-guarded by
    ``mayatk/test/test_blender_bridge.py::TestPullTemplateCopiesMatchTheirSource``.
    """
    import maya.api.OpenMaya as om

    def playback(**flag):
        return cmds.playbackOptions(query=True, **flag)

    return {
        "fps": om.MTime(1.0, om.MTime.kSeconds).asUnits(om.MTime.uiUnit()),
        "frame_start": playback(minTime=True),
        "frame_end": playback(maxTime=True),
        "anim_start": playback(animationStartTime=True),
        "anim_end": playback(animationEndTime=True),
        "frame_current": cmds.currentTime(query=True),
    }


def write_manifest(
    entries,
    visibility,
    node_types,
    scene,
    path,
    lights=(),
    skins=None,
    bones=None,
    shots=None,
    rig=None,
    machinery=None,
):
    """The ONE conversion sidecar, consumed by MayaSceneImport: ``materials`` =
    textures FBX cannot carry; ``visibility`` = smart-bake's baked visibility
    (FBX carries the curve but Blender's importer drops it); ``transforms`` =
    the group/locator node types FBX nulls cannot express; ``scene`` = the
    time setup (fps / ranges / current frame — FBX carries the fps and the
    animation span, Blender's importer reads only the fps); ``lights`` = the
    scene's lights as data (see :func:`scene_lights`); ``skins`` = each skinned
    mesh's skinning method (see :func:`skinning_methods`); ``bones`` = the joint
    hierarchy the skin pre-pass flattened away (see
    :func:`_export_ready_skins`); ``machinery`` = the rig apparatus the bake
    left inert, for the consumer to drop (see :func:`_classify_rig_machinery`).
    One file — same
    producer, same consumer, same lifecycle — not a sidecar per concern.
    Always written: every scene has a time setup.

    File-less material entries are written too: a translated material whose
    texture paths never resolved must surface as a NAMED warning on the Blender
    side, not as silently pink geometry (live production report).
    """
    data = {
        "version": 2,
        "materials": entries,
        "visibility": visibility,
        "transforms": node_types,
        "scene": scene,
        "lights": list(lights),
        "skins": skins or {},
        "bones": bones or {},
        **({"rig": rig} if rig else {}),
        **({"machinery": machinery} if machinery else {}),
    }
    if shots:  # absent = nothing to say; the consumer gates on presence
        data["shots"] = shots
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=1)
    if visibility:
        print(
            "smart_bake: visibility for {} object(s) written to the manifest.".format(
                len(visibility)
            )
        )
    if machinery:
        print(
            "rig: {} baked-rig node(s) named for the consumer to drop.".format(
                len(machinery)
            )
        )


def scene_lights(cmds):
    """The manifest's ``lights`` section: every light in the scene, as data.

    Lights never ride inside the FBX (see the export flags): Blender 5.1's importer
    aborts on the first one. The light transforms still ship as nulls, and the Blender
    side attaches a real light to each (``MayaSceneImport._rebuild_lights``). The
    records come from mayatk's ``BlenderBridge._manifest_lights`` -- the send
    direction's reader, not a copy of it -- so without mayatk importable the scene
    arrives without lights rather than not at all.
    """
    try:
        from mayatk.env_utils.blender_bridge._blender_bridge import BlenderBridge
    except Exception as error:  # noqa: BLE001
        print("lights: mayatk unavailable ({}); not carried.".format(error))
        return []
    try:
        return BlenderBridge()._manifest_lights(
            cmds.ls(type="transform", long=True) or []
        )
    except Exception:  # noqa: BLE001
        print("lights: collection failed; not carried.")
        traceback.print_exc()
        return []


def _detect_complex_anim(cmds):
    """Cheap, dependency-free probe: does the scene hold animation FBX's plain bake
    would lose? A proxy for ``SmartBake.analyze`` used to decide whether the (heavier)
    mayatk import is worth it -- kept in Maya's own modules so a bare mayapy can gate
    without pulling mayatk. Signals: any constraint / expression / IK / motion path,
    any set-driven-key curve (``animCurveU*``), or any animCurve driving a
    ``.visibility`` plug (the inherited-visibility case FBX drops)."""
    if cmds.ls(type=_CONSTRAINT_TYPES + ("expression", "ikHandle", "motionPath")):
        return True
    if cmds.ls(type=("animCurveUL", "animCurveUA", "animCurveUU")):
        return True
    # Visibility is unitless -> animCurveTU; bounded scan (few such curves).
    for crv in cmds.ls(type="animCurveTU") or []:
        for plug in (
            cmds.listConnections(
                crv + ".output", source=False, destination=True, plugs=True
            )
            or []
        ):
            if plug.split(".")[-1] in ("visibility", "v"):
                return True
    return False


def _transfer_rig(cmds, frames):
    """Rig mode (schema 15.2): extract the RigGraph, plan it against the
    CONSUMER's capability (``RIG_CAPABILITY``, sent into this template), smart-
    bake ONLY what the plan says, and sample the built records' targets so the
    consumer can verify what it builds. Returns the manifest's ``rig`` section,
    or ``{}`` when mayatk is unavailable -- printed, never silent. Kept
    dependency-free and IDENTICAL between the FBX and USD templates (guarded)."""
    import json

    if not RIG_CAPABILITY:
        print("rig: no consumer capability was sent; nothing to plan against.")
        return {}
    try:
        from mayatk.rig_utils.rig_graph_extract import RigGraphExtractor
        from pythontk import RigCapability, RigGraph, RigPlanner
    except Exception as error:
        print("rig: mayatk unavailable ({}); rig logic is not carried.".format(error))
        return {}
    try:
        data = RigGraphExtractor().extract()
        graph = RigGraph.from_dict(data)
        plan = RigPlanner.plan(
            graph, RigCapability.from_dict(json.loads(RIG_CAPABILITY))
        )
    except Exception:
        print("rig: extraction or planning failed; rig logic is not carried.")
        traceback.print_exc()
        return {}
    coverage = graph.coverage()
    print(
        "rig: {} record(s); {} to build, {} node(s) to bake, {} unaccounted driver(s).".format(
            len(data["records"]),
            len(plan.build),
            len(plan.bake),
            coverage["unaccounted"],
        )
    )
    path_of = {n["id"]: n.get("path") for n in data["nodes"]}
    bake_paths = [
        path_of[i] for i in plan.bake if path_of.get(i) and cmds.objExists(path_of[i])
    ]
    if bake_paths and INCLUDE_ANIMATION:
        try:
            from mayatk.anim_utils.smart_bake._smart_bake import SmartBake

            result = SmartBake(
                objects=bake_paths,
                use_override_layer=True,
                bake_blend_shapes=True,
                bake_inherited_visibility=False,
                optimize_keys=False,
                restorable=False,
            ).execute()
            print(
                "rig: baked {} object(s) the plan could not build.".format(
                    result.baked_count
                )
            )
        except Exception:
            print("rig: scoped bake failed; unbuilt records arrive static.")
            traceback.print_exc()
    verify_frames = sorted(
        {
            f
            for rid in plan.build
            for f in (plan.verify.get(rid, {}).get("frames") or [])
        }
    )
    if not verify_frames:
        verify_frames = (
            [frames[0], frames[-1]] if frames else [cmds.currentTime(query=True)]
        )
    targets = sorted({i for rid in plan.build for i in graph.record(rid).target_ids()})
    samples = {}
    now = cmds.currentTime(query=True)
    try:
        for frame in verify_frames:
            cmds.currentTime(frame)
            for node_id in targets:
                path = path_of.get(node_id)
                if path and cmds.objExists(path):
                    samples.setdefault(node_id, {})[str(frame)] = cmds.xform(
                        path, query=True, worldSpace=True, translation=True
                    )
    finally:
        cmds.currentTime(now)
    return {
        "graph": data,
        "plan": plan.to_dict(),
        "coverage": coverage,
        "verify_samples": samples,
    }


def _classify_rig_machinery(cmds, rig=None):
    """Answer what each Maya node IS; ``ptk.RigMachinery`` names the apparatus.

    A carrier ships every DAG node as an object, so a rig that could not travel
    arrives TWICE over: its motion, as keys on whatever renders, AND the whole
    apparatus that used to produce that motion -- constraint nodes, IK handles
    and effectors, control curves, up-vector locators, the groups that hold only
    those, and joints nothing content is skinned to. In the target that apparatus
    selects, draws and drives nothing. On the production module it is 924 of 2727
    transforms, landing as ~1100 inert objects around 1505 meshes, which is
    exactly what "the rig is poorly reconstructed" looks like from the outside --
    and it lands identically in BAKE mode, because baking never removed it.

    Named here rather than DELETED here, deliberately. The FBX route bakes before
    it writes, but the USD route has no bake at all (mayaUsd samples the live
    scene per frame), so deleting a constraint on this side would delete the
    motion it was about to sample. What this names, the consumer drops once the
    payload is in: that costs one carrier's worth of nodes and can never cost a
    frame of animation.

    Only the FACTS are Maya's, and they are all this decides: what each node is
    (one of ``RigMachinery.KINDS``, else ``CONTENT`` -- the shape test is a
    DENYLIST, so an unknown shape type counts as content and survives), which
    nodes are load-bearing (every influence of a skinCluster that deforms
    content -- one deforming only the rig's own IK curve protects nothing -- and,
    under ``rig`` mode, every node a BUILT record names, since the consumer
    resolves those ids in the delivered scene), and which nodes ARE the rig (the
    graph's own nodes, plus every constraint and IK node). The rule that turns
    those into an answer -- protection propagating up, the sweep down, ambiguity
    resolved in favour of keeping -- is one shared implementation, so both
    directions of a hand-off can hold the same opinion.

    Parameters:
        cmds: ``maya.cmds``.
        rig: The manifest's ``rig`` section when rig mode built one (schema
            15.3); its graph is reused. Without it the graph is extracted here
            (0.3 s of the census's 1.9 s on the production module), so bake mode
            names the same set.

    Returns:
        dict: ``{maya dag path: kind}``. Empty when nothing qualifies, and empty
        on ANY failure: this is a cleanup, never a reason to lose a conversion.
    """
    machinery_shapes = ("nurbsCurve", "bezierCurve", "locator")
    try:
        from pythontk import RigMachinery
    except Exception as error:
        print(
            "rig: pythontk unavailable ({}); the rig's apparatus travels with "
            "it.".format(error)
        )
        return {}
    try:
        transforms = cmds.ls(type="transform", long=True) or []
        if not transforms:
            return {}
        nodes = {}
        for node in transforms:
            node_type = cmds.nodeType(node)
            shapes = [
                cmds.nodeType(s)
                for s in (
                    cmds.listRelatives(
                        node, shapes=True, fullPath=True, noIntermediate=True
                    )
                    or []
                )
            ]
            if any(s not in machinery_shapes for s in shapes):
                kind = RigMachinery.CONTENT
            elif node_type.endswith("Constraint"):
                kind = "constraint"
            elif node_type in ("ikHandle", "ikEffector"):
                kind = "ik"
            elif node_type == "joint":
                kind = "joint"  # nothing content is skinned to it
            elif shapes:
                kind = "locator" if set(shapes) == {"locator"} else "control"
            else:
                kind = "group"
            nodes[node] = kind

        protected = []
        for skin in cmds.ls(type="skinCluster") or []:
            geometry = cmds.skinCluster(skin, query=True, geometry=True) or []
            if not any(cmds.nodeType(g) not in machinery_shapes for g in geometry):
                continue  # deforms only the rig's own curve: its joints are rig too
            for influence in cmds.skinCluster(skin, query=True, influence=True) or []:
                protected.extend(cmds.ls(influence, long=True) or [])

        graph = (rig or {}).get("graph")
        if graph is None:
            try:
                from mayatk.rig_utils.rig_graph_extract import RigGraphExtractor

                graph = RigGraphExtractor().extract()
            except Exception as error:
                print(
                    "rig: no graph to name the apparatus from ({}); only "
                    "constraint and IK nodes are named.".format(error)
                )
                graph = {}
        path_of = {n.get("id"): n.get("path") for n in graph.get("nodes") or []}
        build = set(((rig or {}).get("plan") or {}).get("build") or [])
        for record in graph.get("records") or []:
            if record.get("id") not in build:
                continue
            ids = [(record.get("target") or {}).get("id")]
            ids += [s.get("id") for s in record.get("sources") or []]
            for node_id in ids:
                path = path_of.get(node_id)
                protected.extend((cmds.ls(path, long=True) or []) if path else ())

        seeds = set()
        for path in path_of.values():
            seeds.update((cmds.ls(path, long=True) or []) if path else ())
        for node_type in ("constraint", "ikHandle", "ikEffector"):
            seeds.update(cmds.ls(type=node_type, long=True) or [])

        kinds = RigMachinery.classify(nodes, seeds=seeds, protected=protected)
        # Every DAG node, not just transforms: a USD payload lands each SHAPE as
        # its own object too, so a shape's name is in the consumer's namespace.
        kinds, dropped = RigMachinery.unambiguous(
            kinds, cmds.ls(dag=True, long=True) or []
        )
        if dropped:
            print(
                "rig: {} apparatus node(s) share a short name with a node that "
                "must survive; kept.".format(len(dropped))
            )
        return kinds
    except Exception:
        print("rig: machinery census failed; the rig's apparatus travels with it.")
        traceback.print_exc()
        return {}


def _inherited_visibility_targets(cmds):
    """Transforms the inherited-visibility bake may touch: those whose OWN
    ``.visibility`` is UNKEYED but that sit under an ancestor whose IS keyed.

    Scoping matters because the bake writes ``.visibility`` keys. Run over every
    transform (``objects=None``) it also re-keys objects that already carry an
    authored visibility curve -- and ``RenderOpacity`` encodes an opacity fade as
    the GAP between two opposite-value ``.visibility`` keys, so any key inserted
    in that gap splits one ramp into several (measured in Unity: two authored
    ramps came back as four, the object flickering in/out/in/out). An object with
    its own curve must NOT be re-keyed for that reason -- but it still has to
    reach Blender, and the FBX cannot carry it (Blender's importer drops
    visibility curves outright -- see :func:`_collect_baked_visibility`). So such
    an object is excluded from the BAKE and collected verbatim instead;
    excluding it from BOTH is how its animation silently stopped arriving. An
    UNKEYED child under a keyed ancestor is the other case: its visibility exists
    only at evaluation time, so only a bake can materialise it.

    Returns long names, the form ``SmartBake`` reports its results under."""
    transforms = cmds.ls(type="transform", long=True) or []
    animated = set()
    for transform in transforms:
        if cmds.listConnections(
            transform + ".visibility",
            source=True,
            destination=False,
            type="animCurve",
        ):
            animated.add(transform)
    if not animated:
        return []
    targets = []
    for transform in transforms:
        if transform in animated:  # own curve -- leave the artist's keys alone
            continue
        ancestor = transform.rsplit("|", 1)[0]
        while ancestor:
            if ancestor in animated:
                targets.append(transform)
                break
            ancestor = ancestor.rsplit("|", 1)[0]
    return targets


def _collect_baked_visibility(cmds, result, authored):
    """Read the baked base-layer visibility curves into a serializable
    ``{short_name: [[frame, value], ...]}`` map.

    FBX *can* carry a visibility curve, but Blender's FBX importer silently drops
    it (verified: even a directly-keyed node arrives with no ``hide_*`` animation),
    so the transform-only FBX is not enough — the values travel to Blender via a
    sidecar the bake / import replays as ``hide_render`` / ``hide_viewport`` keys.
    ``SmartBake`` keys effective inherited visibility onto each mesh's own
    ``.visibility`` on the base layer and reports the curves in
    ``result.visibility_curves``; that is exactly what needs to reach Blender.

    Short names are the map's keys (the Blender-side match convention), so two
    baked objects sharing a short name are ambiguous: the replay would land ONE
    object's curve on BOTH. Identical curves merge fine; differing ones are
    dropped for that name with a warning -- no keys beats wrong keys, and never
    silently (the manifest's named-warning rule).

    *authored* is :func:`_authored_visibility_curves` taken BEFORE the bake --
    passed in rather than re-scanned here, because the scoped pass writes real
    ``.visibility`` curves onto its targets, so a scan run at this point reports
    the keys the bake just made as authored ones."""
    vis = {}
    first_source = {}  # short name -> first contributing long name
    sources = []
    for obj_long, curve in (getattr(result, "visibility_curves", None) or {}).items():
        if not (curve and cmds.objExists(curve)):
            continue
        times = cmds.keyframe(curve, query=True, timeChange=True) or []
        values = cmds.keyframe(curve, query=True, valueChange=True) or []
        sources.append((obj_long, [[t, v] for t, v in zip(times, values)]))
    # The bake deliberately skips objects that already own a visibility
    # curve; their authored keys still have to be carried, and the FBX
    # cannot carry them.
    for obj_long, keys in (authored or {}).items():
        sources.append((obj_long, keys))

    for obj_long, keys in sources:
        if not keys:
            continue
        short = obj_long.split("|")[-1].split(":")[-1]
        if short in vis:
            if vis[short] is not None and vis[short] != keys:
                print(
                    "smart_bake: visibility for duplicate short name {!r} is "
                    "ambiguous ({} vs {}) -- dropped for both.".format(
                        short, first_source[short], obj_long
                    )
                )
                vis[short] = None  # tombstone: later same-name curves stay dropped
            continue
        vis[short] = keys
        first_source[short] = obj_long
    return {short: keys for short, keys in vis.items() if keys is not None}


def _authored_visibility_curves(cmds):
    """``{long_name: [[frame, value], ...]}`` for transforms whose OWN
    ``.visibility`` is keyed.

    Deliberately NOT baked -- re-keying them is what split RenderOpacity fade
    ramps -- but they must still reach Blender: the FBX route cannot carry
    visibility at all, so anything missing from the sidecar never arrives.

    Call it BEFORE the inherited-visibility bake: that pass keys ``.visibility``
    on its targets, and after it "owns a curve" no longer distinguishes an
    artist's keys from the ones the bake just wrote.
    """
    curves = {}
    for transform in cmds.ls(type="transform", long=True) or []:
        plug = transform + ".visibility"
        if not cmds.listConnections(
            plug, source=True, destination=False, type="animCurve"
        ):
            continue
        times = cmds.keyframe(plug, query=True, timeChange=True) or []
        values = cmds.keyframe(plug, query=True, valueChange=True) or []
        keys = [[t, v] for t, v in zip(times, values)]
        if keys:
            curves[transform] = keys
    return curves


class _SkipWholeScene(Exception):
    """Internal: the caller scoped its own bake, so skip the whole-scene pass
    without skipping the visibility collection that follows it."""


def _run_smart_bake(cmds, whole_scene=True):
    """Bake driven channels (inherited visibility, SDKs, constraints, IK, motion
    paths, driven blend shapes) to real keys via mayatk's ``SmartBake`` so the FBX
    carries them. Nondestructive (override layer, flattened by
    ``FBXExportBakeComplexAnimation``); the scene is throwaway so the restore
    manifest is skipped. Guarded: without mayatk on ``PYTHONPATH`` the conversion
    falls back to the plain FBX bake.

    TWO passes, deliberately. The whole-scene pass leaves ``.visibility`` alone
    (``bake_inherited_visibility=False``); inherited visibility is a second pass
    SCOPED to :func:`_inherited_visibility_targets` and narrowed to the
    inherited-visibility channel only, so it neither re-keys an authored fade nor
    duplicates the first pass's work into a second override layer.

    ``whole_scene=False`` runs everything EXCEPT the whole-scene bake: rig mode
    has already baked exactly what its plan could not build (:func:`_transfer_rig`),
    and re-baking the whole scene would undo the point of planning -- but the
    visibility half is a separate carrier concern that must still run, because the
    FBX carries no visibility Blender will read.

    Returns the visibility map (see :func:`_collect_baked_visibility`) for the
    manifest's ``visibility`` section — the scoped bake's curves PLUS the authored
    ones it refuses to touch, so it is non-empty whenever the scene keys
    ``.visibility`` at all. Empty only when mayatk is absent."""
    try:
        from mayatk.anim_utils.smart_bake._smart_bake import SmartBake
    except Exception as error:
        print("smart_bake: mayatk unavailable ({}); plain FBX bake.".format(error))
        return {}
    baked = None
    authored = {}
    # Snapshot the artist's own curves BEFORE the scoped bake writes any -- run
    # afterwards, this same scan re-reads the keys that bake just created (and it
    # repeats the transform walk `_inherited_visibility_targets` does). Its own
    # guard, so the message below never claims a carry that did not happen.
    try:
        authored = _authored_visibility_curves(cmds)
    except Exception:
        print("smart_bake: authored-visibility scan failed; those fades cannot travel.")
        traceback.print_exc()

    # Each pass guards itself: the whole-scene bake below carries constraints, IK,
    # SDKs, motion paths and driven blend shapes, and sharing one `try` with this
    # narrow scoped pass meant a raise here silently cost the export all of them.
    try:
        vis_targets = _inherited_visibility_targets(cmds)
        if vis_targets:
            vis_baker = SmartBake(
                objects=vis_targets,
                use_override_layer=True,
                bake_blend_shapes=False,
                bake_inherited_visibility=True,
                optimize_keys=False,
                restorable=False,
            )
            # Keep the scoped pass to the inherited-visibility channel: these
            # objects ride the whole-scene pass below for everything else.
            vis_only = {}
            for obj, data in vis_baker.analyze().items():
                channel = data.driven_channels.get("inherited_visibility")
                if not channel:
                    continue
                data.driven_channels = {"inherited_visibility": channel}
                data.source_nodes = {
                    k: v
                    for k, v in data.source_nodes.items()
                    if k.startswith("inherited_visibility")
                }
                vis_only[obj] = data
            if vis_only:
                baked = vis_baker.bake(analysis=vis_only)
        print(
            "smart_bake: inherited visibility baked for {} of {} candidate "
            "object(s).".format(
                len(getattr(baked, "visibility_curves", None) or {}),
                len(vis_targets),
            )
        )
    except Exception:
        print(
            "smart_bake: inherited-visibility pre-pass failed; scoped visibility "
            "not baked (authored curves, collected above, still travel)."
        )
        traceback.print_exc()

    try:
        if not whole_scene:
            raise _SkipWholeScene
        result = SmartBake(
            use_override_layer=True,
            bake_blend_shapes=True,
            bake_inherited_visibility=False,
            # Off: the FBX write re-samples this layer on every frame
            # (FBXExportBakeComplexAnimation), so reduced layer keys never reach the
            # file -- the pass was pure cost here. The Blender side reduces the keys
            # that do arrive (MayaSceneImport.import_payload).
            optimize_keys=False,
            restorable=False,
        ).execute()
        # What the bake REFUSED, not every object it looked at: `skipped` also
        # counts the ones that had nothing to bake. A mayatk older than
        # `declined` reports none rather than failing the bake it just made.
        declined = getattr(result, "declined", None) or {}
        print(
            "smart_bake: baked {} object(s) over {} (declined {}).".format(
                result.baked_count, result.time_range, len(declined)
            )
        )
        for name, reason in sorted(declined.items()):
            print("  declined {}: {}".format(name, reason))
    except _SkipWholeScene:
        print("smart_bake: whole-scene bake skipped; the rig plan scoped its own.")
    except Exception:
        print("smart_bake: whole-scene bake failed; plain FBX bake.")
        traceback.print_exc()
    # Collected LAST and UNCONDITIONALLY, because this call also folds in the
    # AUTHORED visibility curves the bake deliberately refuses to touch (see
    # `_authored_visibility_curves`). Those have to travel whether or not the
    # scoped bake found a candidate -- gating the collection on a bake having
    # happened dropped every authored fade in a scene with no unkeyed child
    # under a keyed ancestor, which is the common case, and the FBX cannot
    # carry visibility at all, so anything missing here never arrives.
    try:
        return _collect_baked_visibility(cmds, baked, authored)
    except Exception:
        print("smart_bake: visibility collection failed; none carried.")
        traceback.print_exc()
        return {}


def _progress(done, total, text):
    """A ``pythontk.ProgressRelay`` marker line, flushed so the parent's footer sees it
    while the conversion runs. Spelled out: the marker protocol needs no import."""
    print("::progress:: {}/{} {}".format(done, total, text), flush=True)


def main():
    import maya.standalone

    _progress(0, 6, "Starting Maya")
    maya.standalone.initialize(name="python")
    import maya.cmds as cmds
    import maya.mel as mel

    workspace = _resolve_workspace(cmds, SRC_PATH)
    print("workspace: " + (workspace or "none found (Maya fallback resolution only)"))
    _progress(0, 6, "Opening the scene")
    _open_scene(cmds, SRC_PATH)
    # Read off the ORIGINAL scene, before the skin and smart-bake passes rewrite
    # its curves: the section describes what the artist authored. FBX writes the
    # short name with its namespace.
    shots = shots_section(cmds, lambda name: name.split("|")[-1])
    # Read off the ORIGINAL skins: the skin pass keeps the skinClusters, and the
    # manifest describes what the artist bound.
    skins = skinning_methods(cmds)
    _progress(1, 6, "Preparing skins")
    if INCLUDE_ANIMATION:  # the frames BakeComplexAnimation samples
        start = cmds.playbackOptions(query=True, animationStartTime=True)
        end = cmds.playbackOptions(query=True, animationEndTime=True)
        frames = range(int(round(start)), int(round(end)) + 1)
    else:
        frames = [cmds.currentTime(query=True)]
    bones = _export_ready_skins(cmds, frames, "world")
    # Optional pre-pass: convert driven animation to keys before export (see module
    # docstring). ``True`` forces the attempt; ``"auto"`` gates on the cheap probe.
    visibility, rig = {}, {}
    if RIG_MODE == "rig":
        _progress(2, 6, "Transferring the rig")
        rig = _transfer_rig(cmds, list(frames))
        # Visibility is a CARRIER concern, not a rig one: the FBX writes the
        # curve and Blender's importer drops it, so whatever misses the manifest
        # never arrives. Rig mode replaces smart-bake's WHOLE-SCENE pass (its
        # plan baked exactly what it could not build) -- not this. Without the
        # call, every authored opacity fade vanished the moment rig mode was on.
        if INCLUDE_ANIMATION:
            visibility = _run_smart_bake(cmds, whole_scene=False)
    elif (
        SMART_BAKE
        and INCLUDE_ANIMATION
        and (SMART_BAKE is True or _detect_complex_anim(cmds))
    ):
        _progress(2, 6, "Baking driven animation")
        visibility = _run_smart_bake(cmds)
    # Named now, dropped by the consumer once the payload is in: deleting it
    # HERE would delete the motion the export is about to write. `raw` asks for
    # the scene untouched, and that includes its apparatus.
    machinery = {} if RIG_MODE == "raw" else _classify_rig_machinery(cmds, rig)
    _progress(3, 6, "Translating materials")
    manifest_entries = fbx_safe_materials(cmds)
    lights = scene_lights(cmds)

    if not cmds.pluginInfo("fbxmaya", query=True, loaded=True):
        cmds.loadPlugin("fbxmaya")

    mel.eval("FBXResetExport")  # never inherit whatever preset state this install has
    # Full-fidelity battery -- everything that can ride in the FBX does (mirrors
    # mayatk's established export set, with cameras/lights ON: this is a whole-
    # scene import, not an asset export). Per-flag tolerance: an FBX plugin
    # version missing one command must not kill the conversion.
    for flag in (
        "FBXExportSmoothingGroups -v true",
        # All-hard dense meshes hang the exporter with HardEdges on -- keep it off.
        "FBXExportHardEdges -v false",
        "FBXExportSmoothMesh -v true",
        "FBXExportTangents -v true",
        "FBXExportInstances -v true",
        "FBXExportSkins -v true",
        "FBXExportShapes -v true",
        "FBXExportSkeletonDefinitions -v true",
        "FBXExportCameras -v true",
        # Off: ONE light in the FBX aborts Blender 5.1's importer outright
        # (lamp.cycles.cast_shadow, removed in Cycles 5.x -- measured on a
        # production pull: 4 area lights, nothing imported). Lights travel in the
        # manifest instead (scene_lights); their transforms still ship as nulls.
        "FBXExportLights -v false",
        "FBXExportInputConnections -v true",
        "FBXExportEmbeddedTextures -v " + ("true" if EMBED_TEXTURES else "false"),
        "FBXExportBakeComplexAnimation -v "
        + ("true" if INCLUDE_ANIMATION else "false"),
    ):
        try:
            mel.eval(flag)
        except Exception:
            print("FBX flag skipped (unsupported by this plugin): " + flag)
    _progress(4, 6, "Writing the FBX")
    mel.eval('FBXExport -f "{}"'.format(OUT_FBX))
    # Written only after a successful export (a manifest implies its FBX).
    _progress(5, 6, "Writing the manifest")
    write_manifest(
        manifest_entries,
        visibility,
        scene_node_types(cmds),
        scene_settings(cmds),
        OUT_FBX + ".manifest.json",
        lights=lights,
        skins=skins,
        bones=bones,
        shots=shots,
        rig=rig,
        machinery=machinery,
    )
    _progress(6, 6, "Converted")


def shots_section(cmds, spell):
    """The scene's shots as the manifest's ``shots`` section, or ``None``.

    Neither carrier has a place for a shot, a marker, a locked gap or the samples
    the sequencer planted on shot bounds, so the store crosses as data and
    ``MayaSceneImport`` rebuilds it 1:1. mayatk's store encodes it
    (``ShotStore.export_transfer`` over ``pythontk.ShotTransfer``), names spelled
    by *spell* as the carrier will write them. Guarded like the other mayatk
    pre-passes: without mayatk on ``PYTHONPATH`` the shots are not carried, and a
    printed line says so.
    """
    try:
        from mayatk.anim_utils.shots._shots import ShotStore
    except Exception as error:  # noqa: BLE001 -- degrade, never fail the conversion
        print("shots: mayatk unavailable ({}); not carried.".format(error))
        return None
    try:
        return ShotStore.export_transfer(spell=spell)
    except Exception:  # noqa: BLE001
        print("shots: could not read the scene's shots; not carried:")
        traceback.print_exc()
        return None


def _exit(code):
    """Leave without teardown. ``os._exit`` is not enough on Windows: it still runs
    every DLL's detach, where Maya's static destructors fault and its crash handler
    saves the open scene into the temp dir -- a 366 MB ``[Recovered]`` copy per
    production conversion (measured). ``pythontk.ProcessExit`` skips detach; without
    pythontk on the path this degrades to ``os._exit``."""
    sys.stdout.flush()
    sys.stderr.flush()
    try:
        from pythontk.core_utils.process_exit import ProcessExit
    except Exception:  # noqa: BLE001 -- the exit must never raise
        os._exit(code)
    ProcessExit.hard_exit(code)


def _withhold(artifact):
    """Remove *artifact* and its sidecar after a failed run: whatever it left
    behind must never pass as the conversion.

    Success is judged by the artifact, and an exporter can fail AFTER opening its
    file -- Maya's USD exporter writes a layer before it refuses a scene
    (measured: a root-level joint), so the partial payload passed, the non-zero exit was
    tolerated as a teardown crash, and the caller reported a missing sidecar in
    place of the exporter's own message. A payload whose sidecar failed is as
    wrong: it imports without what the sidecar rebuilds."""
    for path in (artifact, artifact + ".manifest.json"):
        try:
            os.remove(path)
        except OSError:
            pass


try:
    main()
except Exception:
    traceback.print_exc()
    _withhold(OUT_FBX)
    _exit(1)
# Success is judged by the artifact; skip standalone teardown (known access violations).
_exit(0)
