# Blender selection -> .ma/.mb save script (Blender -> Maya). Generated by MayaBridge -- do not edit by hand.

"""Import the bridged FBX into a headless ``mayapy`` and save it as a Maya scene.

The ``save_as`` half of the Blender->Maya hand-off: same FBX payload and same
``.manifest.json`` sidecar the interactive ``import`` template consumes, but delivered to
``mayapy`` so the Blender artist ends up with a real ``.ma`` on disk instead of an open
Maya session. Nothing here re-implements the send -- ``MayaBridge`` produces the payload
exactly once, for both modes. ``mayapy`` (not ``maya -batch``) is the ecosystem's headless
Maya route, shared with the pull-direction conversion.

Run through :class:`pythontk.ScriptRunDeliverer` (which wraps ``run_script_to_artifact``),
so success is judged by the saved scene's existence -- NOT the exit code: standalone
teardown is a known crasher, hence the ``os._exit`` below, which skips it entirely.

The save starts from a new empty scene: whatever ``initialize()`` leaves behind must not
land in a file the artist thinks contains only their selection. Mirror of mayatk's
``templates/_bake_scene.py`` (which writes the same kind of artifact for the reference
cache) and of mayatk's own ``_save_scene.py`` running the other direction.

Post-import repairs match the interactive ``import`` template exactly, because the same
FBX has the same two lossy spots:

- **Parent Empties -> plain groups.** Blender Empties travel as FBX nulls and Maya's
  importer gives every null a locator shape. Delegated to the paired engine's
  ``BlenderSceneImport._restore_empty_groups`` when mayatk is importable, with a
  dependency-free fallback so a bare ``mayapy`` still saves a clean hierarchy.
- **Native material rebuild.** Blender's FBX exporter carries only images wired (almost)
  directly into Principled sockets, so real production materials arrive gray; the sidecar
  carries each material's ORIGINAL image files and is replayed through the ONE existing
  applier, ``mayatk.BlenderSceneImport._apply_texture_manifest``. Without mayatk in the
  child the FBX's classic-model materials are kept and a console line says so.

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to ``MayaBridge.save_as``).
"""

# Bridge metadata -- consumed by MayaBridge before substitution.
BRIDGE_MODES = ("save_as",)

# Dependency-free Maya Python at module scope: no mayatk/blendertk/pythontk imports (the
# target machine's mayapy only has Maya's own modules). mayatk is imported OPTIONALLY,
# inside the engine step, and its absence is never fatal.
import os
import sys
import traceback

FBX_PATH = r"__FBX_PATH__"
OUT_FILE = r"__OUT_FILE__"
# Roots for mayatk + pythontk, resolved in the parent Blender -- the child must not
# depend on its own environment to import the toolkit (mirror of btk's import template).
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__
# Which Maya shader the manifest rebuild targets (GameShader's vocabulary:
# standard_surface / open_pbr / stingray).
SHADER_TYPE = __SHADER_TYPE__


def _extend_sys_path():
    """Make mayatk/pythontk importable here (mirror of the import template)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def _engine():
    """The mayatk import engine, or None when mayatk is not importable in this child.

    Reusing it keeps the save's FBX import + material rebuild byte-identical to the
    interactive import path instead of maintaining a second copy of that logic here.
    """
    _extend_sys_path()
    try:
        from mayatk.env_utils.blender_bridge._scene_import import BlenderSceneImport

        return BlenderSceneImport(log_level="WARNING")
    except Exception as error:
        print(
            "mayatk unavailable ({}); using the plain FBX import path.".format(error)
        )
        return None


def import_fbx(cmds, mel, engine):
    """Import the payload deterministically; return ALL new nodes.

    All nodes, not just transforms: the manifest rebuild needs the shading engines.
    The FBX plugin's import options are global and sticky, and the factory "merge" mode
    can RETARGET animation onto same-named nodes -- the engine's ``_import_fbx`` resets
    them; the fallback below repeats that reset inline for a bare mayapy.
    """
    if engine is not None:
        return engine._import_fbx(FBX_PATH)
    if not cmds.pluginInfo("fbxmaya", query=True, loaded=True):
        cmds.loadPlugin("fbxmaya")
    for command in ("FBXResetImport", "FBXImportMode -v add"):
        try:
            mel.eval(command)
        except Exception:
            print("FBX import option skipped (unsupported by this plugin): " + command)
    return (
        cmds.file(FBX_PATH, i=True, type="FBX", ignoreVersion=True, returnNewNodes=True)
        or []
    )


def restore_empty_groups(cmds, engine, new_nodes):
    """Restore imported Empties as the correct Maya node types (see module docstring).

    The engine path honors the manifest's ``empties`` section (author-marked
    locators survive as locators even with children). The dependency-free
    fallback keeps the children-based heuristic only -- a machine without
    mayatk has already lost the material rebuild, and the heuristic is the
    right default for unmarked Empties.
    """
    if engine is not None:
        try:
            engine._restore_empty_groups(new_nodes, FBX_PATH + ".manifest.json")
            return
        except Exception:
            print("Empty-group repair failed in the engine; falling back:")
            traceback.print_exc()
    for shape in cmds.ls(new_nodes, exactType="locator", long=True) or []:
        transform = (cmds.listRelatives(shape, parent=True, fullPath=True) or [None])[0]
        if not transform:
            continue
        if len(cmds.listRelatives(transform, shapes=True, fullPath=True) or []) != 1:
            continue
        if cmds.listRelatives(transform, children=True, type="transform", fullPath=True):
            cmds.delete(shape)


def rebuild_materials(engine, new_nodes):
    """Replay the sidecar manifest through mayatk's applier (see module docstring).

    Best-effort by contract: a save whose materials stay classic-model is a fidelity
    loss, not a failure, and must never cost the user the saved scene.
    """
    manifest = FBX_PATH + ".manifest.json"
    if engine is None or not os.path.isfile(manifest):
        return
    try:
        engine._apply_texture_manifest(manifest, new_nodes, shader_type=SHADER_TYPE)
    except Exception:
        print("Texture-manifest rebuild failed; keeping FBX materials:")
        traceback.print_exc()


def main():
    import maya.standalone

    maya.standalone.initialize(name="python")
    import maya.cmds as cmds
    import maya.mel as mel

    cmds.file(new=True, force=True)
    engine = _engine()
    new_nodes = import_fbx(cmds, mel, engine)
    restore_empty_groups(cmds, engine, new_nodes)
    rebuild_materials(engine, new_nodes)

    # The extension the caller asked for decides the writer: .mb only when explicitly
    # requested, since a .ma is diffable, greppable, and survives a version bump.
    file_type = "mayaBinary" if OUT_FILE.lower().endswith(".mb") else "mayaAscii"
    cmds.file(rename=OUT_FILE)
    cmds.file(save=True, type=file_type, force=True)
    print("Saved {} node(s) into {}".format(len(new_nodes), OUT_FILE))


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; skip standalone teardown (known access violations).
sys.stdout.flush()
os._exit(0)
