# Maya import script (Blender -> Maya bridge). Generated by MayaBridge -- do not edit by hand.

"""Import the bridged payload (FBX or USD) into Maya, with optional clean-slate and
frame-on-import behaviors.

The single Maya-side recipe for the bridge. Two booleans pick the variant the artist wants
(this replaces what used to be three near-identical templates):

- ``CLEAR_SCENE`` -- open a new (empty) Maya scene first (clean-slate hand-off).
- ``FRAME_VIEW``  -- after import, select the new top-level objects and frame them (viewFit).

With both off this is a plain additive import into the current scene; both on clears then frames.

Post-import repairs (both best-effort -- a repair must never cost the user the import):

- **Empties -> correct Maya node types.** Blender Empties travel as FBX nulls and Maya's
  importer gives every null a locator shape, so a sent group hierarchy arrived as locators
  (live production report). An Empty WITH children is a Maya group (locator shape dropped); a
  childless Empty stays a locator (it marks a point); the manifest's ``empties`` section
  overrides the heuristic where the author marked intent (non-default display type, or the
  ``maya_node_type`` tag a round-tripped scene carries). Delegated to the pull direction's
  engine, ``mayatk.BlenderSceneImport._restore_empty_groups``, with the children heuristic as
  the dependency-free fallback (the same loop ``_save_scene.py`` carries, guarded by mayatk's
  suite).
- **Native material rebuild.** Blender's FBX exporter only carries images wired (almost)
  directly into Principled sockets -- packed ORM/MSAO through SeparateColor, AO multiplies and
  node-group plumbing export as NOTHING, so real production materials arrived gray. MayaBridge
  now writes the same ``.manifest.json`` sidecar the pull direction uses (each material's
  ORIGINAL image files), and this script replays it through the ONE existing applier,
  ``mayatk.BlenderSceneImport._apply_texture_manifest`` (the established template->paired-engine
  contract; see both ``_bake_scene.py`` templates). Without mayatk on the target Maya the FBX's
  classic-model materials are kept, with a console line saying so.
"""

# Bridge metadata -- consumed by MayaBridge before substitution.
BRIDGE_MODES = ("send_to",)

# Export settings applied Blender-side before launch (read by MayaBridge; echoed here so the panel
# exposes them): scope=__SCOPE__ carrier=__CARRIER__ materials=__INCLUDE_MATERIALS__ embed_textures=__EMBED_TEXTURES__ apply_unit_scale=__APPLY_UNIT_SCALE__ include_animation=__INCLUDE_ANIMATION__ triangulate=__TRIANGULATE__ scene_data=__INCLUDE_SCENE_DATA__
#
# ``shots`` changes what rides beside the FBX: on, the scene's shots travel in the
# manifest and mayatk rebuilds them 1:1 in its Shot Sequencer.
import os
import sys
import traceback

import maya.cmds as cmds
import maya.mel as mel

# The payload: FBX or USD, routed on the extension below. ``FBX_PATH`` is the
# historical name of the same path; the sidecar manifest hangs off it either way.
FBX_PATH = r"__PAYLOAD_PATH__"
USD_EXTENSIONS = (".usd", ".usda", ".usdc", ".usdz")
CARRIER = "usd" if FBX_PATH.lower().endswith(USD_EXTENSIONS) else "fbx"
# Roots for mayatk + pythontk, resolved in the parent Blender -- the child must not
# depend on its own environment to import the toolkit (mirror of mtk's template).
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__
CLEAR_SCENE = __CLEAR_SCENE__
FRAME_VIEW = __FRAME_VIEW__
# Which Maya shader the manifest rebuild targets (GameShader's vocabulary:
# standard_surface / open_pbr / stingray).
SHADER_TYPE = __SHADER_TYPE__


# The *USD Import* translator options every hand-off importer uses -- mirror of
# mayatk ``UsdUtils.INTERCHANGE_IMPORT_OPTIONS`` (pinned equal): time samples as
# keys (the translator's default is OFF -- every animated prim arrived static,
# measured) and Blender's ``st`` (its exporter's name for the render-active UV
# map) landing as Maya's ``map1``, the FBX route's spelling.
USD_IMPORT_OPTIONS = "readAnimData=1;remapUVSetsTo=[[st,map1]]"


def import_fbx():
    """Import the payload deterministically; return the nodes it created.

    The FBX plugin's import options are global and sticky (the user's last
    interactive import shapes this one), and the factory "merge" mode can
    RETARGET animation onto same-named nodes already in the scene -- reset,
    then pin "add". Mirror of the pull engine's ``_import_fbx``; best-effort
    per command so a plugin build missing one can't block the import.

    ``FBXResetImport`` restores the factory take selector, which on Maya 2025
    is "No Animation" -- so the reset itself drops every animCurve unless the
    take is re-selected. Index ``-1`` is resolved per file at import time (last
    take, or none for a takeless file); a FIXED index aborts a takeless import
    and empties it. See mayatk ``FbxUtils.reset_import``.
    """
    for command in (
        "FBXResetImport",
        "FBXImportMode -v add",
        "FBXImportSetTake -ti -1",
    ):
        try:
            mel.eval(command)
        except Exception:
            print("FBX import option skipped (unsupported by this plugin): " + command)
    return (
        cmds.file(FBX_PATH, i=True, type="FBX", ignoreVersion=True, returnNewNodes=True)
        or []
    )


def import_usd():
    """Import a USD payload through mayaUsd's file translator; return the new nodes.

    The translator honors the active namespace like the FBX path and needs no
    sticky-option reset -- USD import options travel on the call.
    """
    if not cmds.pluginInfo("mayaUsdPlugin", query=True, loaded=True):
        cmds.loadPlugin("mayaUsdPlugin")
    return (
        cmds.file(
            FBX_PATH.replace("\\", "/"),
            i=True,
            type="USD Import",
            ignoreVersion=True,
            returnNewNodes=True,
            options=USD_IMPORT_OPTIONS,
        )
        or []
    )


def import_payload():
    """Run the importer the payload's extension names (FBX or USD)."""
    if CARRIER == "usd":
        return import_usd()
    if not cmds.pluginInfo("fbxmaya", query=True, loaded=True):
        cmds.loadPlugin("fbxmaya")
    return import_fbx()


def restore_usd_locators(new_nodes):
    """Give the Empties that mark a point their locator shape back (USD carrier).

    Off a USD layer every Blender Empty arrives as a SHAPELESS transform --
    groups are already right, point markers are invisible and unpickable. The
    engine path honors the manifest's ``empties`` section; the dependency-free
    fallback keeps the children heuristic (childless -> locator). Kept in step
    by hand with ``mayatk.BlenderSceneImport._restore_usd_locators``.
    """
    _extend_sys_path()
    try:
        from mayatk.env_utils.blender_bridge._scene_import import BlenderSceneImport

        BlenderSceneImport._restore_usd_locators(new_nodes, FBX_PATH + ".manifest.json")
        return
    except Exception as error:
        print(
            "Locator repair via mayatk unavailable ({}); using the heuristic.".format(
                error
            )
        )
    # exactType: a joint IS a transform, and a shapeless leaf joint is a
    # skeleton tip, not a point marker.
    for transform in cmds.ls(new_nodes, exactType="transform", long=True) or []:
        if cmds.listRelatives(transform, shapes=True, fullPath=True):
            continue
        if cmds.listRelatives(
            transform, children=True, type="transform", fullPath=True
        ):
            continue
        short = transform.rsplit("|", 1)[-1].rsplit(":", 1)[-1]
        cmds.createNode("locator", name=short + "Shape", parent=transform)


def restore_empty_groups(new_nodes):
    """Strip the locator shape from imported Empties that are groups (FBX carrier).

    Maya's FBX importer gives every null a locator shape, so a sent group
    hierarchy arrived as locators. The engine path --
    ``mayatk.BlenderSceneImport._restore_empty_groups`` -- honors the manifest's
    ``empties`` section (an author-marked locator survives even with children);
    the dependency-free fallback keeps the children heuristic. That loop is held
    token-identical to ``_save_scene.py``'s and executed against the engine by
    mayatk's suite.
    """
    _extend_sys_path()
    try:
        from mayatk.env_utils.blender_bridge._scene_import import BlenderSceneImport

        BlenderSceneImport._restore_empty_groups(new_nodes, FBX_PATH + ".manifest.json")
        return
    except Exception as error:
        print(
            "Empty-group repair via mayatk unavailable ({}); using the heuristic.".format(
                error
            )
        )
    for shape in cmds.ls(new_nodes, exactType="locator", long=True) or []:
        transform = (cmds.listRelatives(shape, parent=True, fullPath=True) or [None])[0]
        if not transform:
            continue
        if len(cmds.listRelatives(transform, shapes=True, fullPath=True) or []) != 1:
            continue
        if cmds.listRelatives(
            transform, children=True, type="transform", fullPath=True
        ):
            cmds.delete(shape)


def _extend_sys_path():
    """Make mayatk/pythontk importable here (mirror of mtk's import template)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def rebuild_materials(new_nodes):
    """Replay the sidecar manifest through mayatk's applier (see module docstring)."""
    manifest = FBX_PATH + ".manifest.json"
    if not os.path.isfile(manifest):
        return
    _extend_sys_path()
    try:
        from mayatk.env_utils.blender_bridge._scene_import import BlenderSceneImport
    except Exception as error:
        print(
            "mayatk unavailable ({}); keeping the FBX-carried materials.".format(error)
        )
        return
    try:
        BlenderSceneImport(log_level="WARNING")._apply_texture_manifest(
            manifest, new_nodes, shader_type=SHADER_TYPE, carrier=CARRIER
        )
    except Exception:
        print("Texture-manifest rebuild failed; keeping the carried materials:")
        traceback.print_exc()


def rebuild_scene_data(new_nodes):
    """Land the sent scene's records -- its shots, its emissive groups -- from the
    sidecar's ``shots`` / ``records`` sections through mayatk's applier (mirror of
    ``rebuild_materials``): 1:1 in Maya's Shot Sequencer and Emissive Groups,
    memberships scoped to what arrived. Best-effort by contract.
    """
    manifest = FBX_PATH + ".manifest.json"
    if not os.path.isfile(manifest):
        return
    _extend_sys_path()
    try:
        from mayatk.env_utils.blender_bridge._scene_import import BlenderSceneImport
    except Exception as error:
        print(
            "mayatk unavailable ({}); the sent scene data is not landed.".format(error)
        )
        return
    try:
        BlenderSceneImport(log_level="WARNING")._apply_scene_data(
            manifest, new_nodes, carrier=CARRIER
        )
    except Exception:
        print("Scene-data landing failed; the scene keeps its own:")
        traceback.print_exc()


def main():
    if CLEAR_SCENE:
        cmds.file(new=True, force=True)

    new_nodes = import_payload()
    # Each carrier gets the Empties wrong in its own way: FBX makes every null a
    # locator (strip the groups' shapes), USD makes every Empty shapeless (give
    # the point markers theirs back). Same manifest rules decide both.
    if CARRIER == "usd":
        restore_usd_locators(new_nodes)
    else:
        restore_empty_groups(new_nodes)
    rebuild_materials(new_nodes)
    rebuild_scene_data(new_nodes)

    if not FRAME_VIEW:
        return

    tops = [n for n in (cmds.ls(new_nodes, assemblies=True) or []) if cmds.objExists(n)]
    if tops:
        cmds.select(tops, replace=True)
    try:
        cmds.viewFit()
    except Exception:
        pass


main()
