# Maya import + frame script (Blender -> Maya bridge). Generated by MayaBridge -- do not edit.

"""Import the bridged FBX, select the new top-level objects, and frame them in the viewport."""

# Bridge metadata -- consumed by MayaBridge before substitution.
BRIDGE_MODES = ("send_to",)

# Export settings applied Blender-side before launch (read by MayaBridge; echoed here so the panel
# exposes them): materials=__INCLUDE_MATERIALS__ embed_textures=__EMBED_TEXTURES__ apply_unit_scale=__APPLY_UNIT_SCALE__ include_animation=__INCLUDE_ANIMATION__ triangulate=__TRIANGULATE__
import maya.cmds as cmds
import maya.mel as mel

FBX_PATH = r"__FBX_PATH__"
FRAME_VIEW = __FRAME_VIEW__


def main():
    if not cmds.pluginInfo("fbxmaya", query=True, loaded=True):
        cmds.loadPlugin("fbxmaya")
    before = set(cmds.ls(assemblies=True) or [])
    mel.eval('FBXImport -f "{}"'.format(FBX_PATH))
    new = [n for n in (cmds.ls(assemblies=True) or []) if n not in before]
    if new:
        cmds.select(new, replace=True)
    if FRAME_VIEW:
        try:
            cmds.viewFit()
        except Exception:
            pass


main()
