# Maya import script (Blender -> Maya bridge). Generated by MayaBridge -- do not edit by hand.

"""Import the bridged FBX into Maya, with optional clean-slate and frame-on-import behaviors.

The single Maya-side recipe for the bridge. Two booleans pick the variant the artist wants
(this replaces what used to be three near-identical templates):

- ``CLEAR_SCENE`` -- open a new (empty) Maya scene first (clean-slate hand-off).
- ``FRAME_VIEW``  -- after import, select the new top-level objects and frame them (viewFit).

With both off this is a plain additive import into the current scene; both on clears then frames."""

# Bridge metadata -- consumed by MayaBridge before substitution.
BRIDGE_MODES = ("send_to",)

# Export settings applied Blender-side before launch (read by MayaBridge; echoed here so the panel
# exposes them): materials=__INCLUDE_MATERIALS__ embed_textures=__EMBED_TEXTURES__ apply_unit_scale=__APPLY_UNIT_SCALE__ include_animation=__INCLUDE_ANIMATION__ triangulate=__TRIANGULATE__
import maya.cmds as cmds
import maya.mel as mel

FBX_PATH = r"__FBX_PATH__"
CLEAR_SCENE = __CLEAR_SCENE__
FRAME_VIEW = __FRAME_VIEW__


def main():
    if CLEAR_SCENE:
        cmds.file(new=True, force=True)
    if not cmds.pluginInfo("fbxmaya", query=True, loaded=True):
        cmds.loadPlugin("fbxmaya")

    before = set(cmds.ls(assemblies=True) or [])
    mel.eval('FBXImport -f "{}"'.format(FBX_PATH))

    if not FRAME_VIEW:
        return

    new = [n for n in (cmds.ls(assemblies=True) or []) if n not in before]
    if new:
        cmds.select(new, replace=True)
    try:
        cmds.viewFit()
    except Exception:
        pass


main()
