# Maya new-scene import (Blender -> Maya bridge). Generated by MayaBridge -- do not edit by hand.

"""Open a new (empty) Maya scene, then import the bridged FBX -- a clean-slate hand-off when the
selection is meant to replace what's in Maya rather than add to it."""

# Bridge metadata -- consumed by MayaBridge before substitution.
BRIDGE_MODES = ("send_to",)

# Export settings applied Blender-side before launch (read by MayaBridge; echoed here so the panel
# exposes them): materials=__INCLUDE_MATERIALS__ embed_textures=__EMBED_TEXTURES__ apply_unit_scale=__APPLY_UNIT_SCALE__ include_animation=__INCLUDE_ANIMATION__ triangulate=__TRIANGULATE__
import maya.cmds as cmds
import maya.mel as mel

FBX_PATH = r"__FBX_PATH__"


def main():
    cmds.file(new=True, force=True)
    if not cmds.pluginInfo("fbxmaya", query=True, loaded=True):
        cmds.loadPlugin("fbxmaya")
    mel.eval('FBXImport -f "{}"'.format(FBX_PATH))


main()
